static/data/mods.json, static/data/systems.json
Did a pass on HA, also fixed some things I missed earlier
- SSC Death's Head Core Siphon was incorrectly assigned to SSC Dusk Wing
- HORUS Pegasus's SISYPHUS NHP was incorrectly assigned to HA Genghis
**Barbarossa:**
- Flak Launcher was typo'd as a "Systen"
**Napoleon:**
- Phasing Mod: LL was 1, is 2
**Saladin:**
- Paracausal Mod: LL was 2, is 3
=> HA + other compendium fixes

package.json, src/renderer/store/data_io.js
replace the copyRecursive io function with fs-extra's copySync, which allows copying directories between devices
this caused a kinda nasty bug when a user tried to do this where it'd create the empty homebrew folder then fail to copy the brew to it, breaking further attempts to load the brew even if they put the source folder in the same device as userdata
=>  replace copyRecursive with fs-extra's copySync

.travis.yml, package.json
- Add a build pipeline on Travis; builds off stable, beta,
and tso_ci_pipeline (for testing)
- On completion, Travis will push build artifacts back to a GitHub draft release
if there is one with a version number matching the package.json version
- Turned on creating Linux builds
=> Build on Travis; add Linux dist

src/main/index.js
This gives us an "About" panel on OSX that just points to an Electron placeholder.  Can dump that if you like.
We should check that menus still aren't visible on Windows.
=> OSX Menus & Bug Fixes

.travis.yml, package.json
- Added Win32 compatability.  Builds in the same exe as 64, so size
is now near 140mb.  Not a lot I see to make that smaller right now.
- Rewrote the Travis settings to do three builds in parallel (Win,
OSX, Linux).  This shortens the overall build time.
=> Add Win32, refactor CI to be more parallel

.gitignore, .travis.yml, build_scripts/build.sh, build_scripts/create-version-env.ts, package.json
Lots going on here!
From an end-user (i.e. dev) perspective, check out the package.json for a couple changes to script names.  Additionally, doing a `yarn dist` will now put your build into `/build/local-build/`.  The `yarn dist-travis` command will only work in a travis environment, and gets called by the shell script.
The mess of stuff we're now doing with environment variables is to let us name folders in the same fashion they already are on itch, but based on gleaning this info from the environment.
I tested this pretty thoroughly from a Travis / itch perspective, and realized tonight there were some bugs left in doing local `yarn dist` builds.  I think I fixed it all, but let me know if you see any issues.
=> Automatically push release to itch.io

src/renderer/features/pilot_management/classes/mech/MechLoadout.ts, src/renderer/features/pilot_management/classes/mech/Mount.ts
- Fixes the `MechLoadout` SP getter not counting Improved Armament & Integrated Weapon CBs
- Fixes the `Mount` weapons getter not counting the 2nd aux on flex mounts, since it was using `this.weapons` rather than `this.Weapons`
Fixes #232
=> Weapon SP fixes

src/renderer/features/pilot_management/ConfigSheet/LoadoutEditor/IntegratedBlock.vue
Tags of items in the integrated block of mech loadouts weren't being passed a pilot so things like bonus limited systems weren't being calculated properly.
=> Pass pilot to tags in integrated block of mech loadout

src/main/index.js, src/renderer/features/pilot_management/ConfigSheet/index.vue, src/renderer/features/pilot_management/PilotSheet/index.vue
- removed clear button from long form text inputs such as pilot history
- don't have a mac to test this but i added undo/redo options to the electron menu which should fix the shortcuts not working in macOS
=> text area tweaks

src/renderer/features/pilot_management/PilotSheet/Selectors/LevelSelector.vue, src/renderer/features/pilot_management/PilotSheet/index.vue, src/renderer/features/pilot_management/classes/Pilot.ts
Instead of clearing all selections, will simply highlight point counters with warning colour (same as when there are points left to spend after an unguided level up).
Basically the simplest implementation of #286 I could see.
=> Preserve spent points when leveled down

src/renderer/features/pilot_management/RosterView/AddPilotMenu.vue, src/renderer/features/pilot_management/components/UI/LazyDialog.vue
Uses bidirectional watch to separate prop from datamodel. 
This way the components can notify parents when they've been dismissed by clicking outside them, without causing Bad Things™ to happen by directly modifying their own props.
Vuetify 2.0 comes with a click:outside event that should obsolete this, from what I've read? 
Should partially take care of #158 and #267 where affected by LazyDialog. Since I spotted it, I also gave the same treatment to AddPilotMenu. There may some more in the GM Toolkit that would need this.
First time touching Vue code, so please tell me if this does something monumentally stupid eh?
=> Small hack to easily dismiss LazyLoad dialogs

src/renderer/features/pilot_management/ConfigSheet/LoadoutEditor/MechWeaponItem.vue
Fixed some issues with the Mod button changes I made.  It now:
- stays active all the time, in case you want to get in there and put a mod on that you shouldn't technically have
- changes colors correctly
I'm guessing @jarena3 you don't care about the styling on it, since you're reworking that.  But if you want me to change anything, let me know.
Screenshot above shows a mount with an eligible mod and the lower slot without an eligible mod.
=> Fix weapon mod button.  Not sure what I was thinking.

src/renderer/features/pilot_management/RosterView/AddPilotMenu.vue
The Import Cloud ID field wasn't set to autofocus. It's the only input field available and it's initiated directly by user input, so I think saving a click would be a good idea.
=> Autofocus input field

src/renderer/features/gm_toolkit/vuetify_theme.ts
Adds a role colour for Biological NPCs (Monstrosities and Infantry Squads). Should be pulled at the same time as PR#71 on lancer-data so that these NPCs display properly.
=> Add Biological NPCs

package.json, src/renderer/features/_shared/store/index.ts, src/renderer/features/_shared/topbar/Pages/OptionsPage.vue, src/renderer/features/_shared/topbar/index.vue, src/renderer/features/gm_toolkit/store/encounterBuilder.ts, src/renderer/features/gm_toolkit/store/encounterRunner.ts, src/renderer/features/gm_toolkit/store/index.ts, src/renderer/features/gm_toolkit/store/npcDesigner.ts, src/renderer/features/gm_toolkit/views/EncounterRunner/EncounterRunner.vue, src/renderer/features/gm_toolkit/views/Home.vue, src/renderer/features/main_menu/index.vue, src/renderer/features/pilot_management/index.vue, src/renderer/features/pilot_management/store/index.ts, src/renderer/store.ts, yarn.lock
Implements [vuex-module-decorators](https://github.com/championswimmer/vuex-module-decorators) and refactors existing Vuex store modules to use those features. 
Should provide parsable, type-safe store accessors that are easier for us, TS and IntelliSense and other tools to work with, and provide more debug info when something goes wrong. 
Only has a couple of examples of use in components, including in `src/renderer/features/gm_toolkit/views/Home.vue`. The module accessors can also be loaded as a data property and used that way, but this is more beneficial when using class-style components.
=> Vuex decorations

src/renderer/features/pilot_management/ConfigSheet/SheetComponents/ImageSelector.vue
stops direct prop manipulation caused by the v-dialog's v-model binding
=> cheeky two-way watcher trick to fix image selector 

src/renderer/features/nav/index.vue, src/renderer/features/pilot_management/ActiveSheet/index.vue, src/renderer/features/pilot_management/Level/index.vue, src/renderer/features/pilot_management/Level/pages/ConfirmPage.vue, src/renderer/features/pilot_management/PilotSheet/components/DeletePilotDialog.vue, src/renderer/features/pilot_management/PilotSheet/components/PilotHeader.vue, src/renderer/features/pilot_management/PilotSheet/components/PilotNav.vue, src/renderer/features/pilot_management/PilotSheet/components/PrintDialog.vue, src/renderer/features/pilot_management/PilotSheet/index.vue, src/renderer/features/pilot_management/PilotSheet/layouts/index.vue, src/renderer/features/pilot_management/PilotSheet/sections/hangar/index.vue, src/renderer/features/pilot_management/PilotSheet/sections/info/components/AppearanceBlock.vue, src/renderer/features/pilot_management/PilotSheet/sections/info/components/HistoryBlock.vue, src/renderer/features/pilot_management/PilotSheet/sections/info/components/IdentBlock.vue, src/renderer/features/pilot_management/PilotSheet/sections/info/components/ImageBlock.vue, src/renderer/features/pilot_management/PilotSheet/sections/info/components/NotesBlock.vue, src/renderer/features/pilot_management/PilotSheet/sections/mech/index.vue, src/renderer/features/pilot_management/Print/PilotPrint.vue, src/renderer/features/pilot_management/Print/index.vue, src/renderer/features/pilot_management/Roster/components/PilotListItem.vue, src/renderer/features/pilot_management/Roster/components/PilotTable.vue, src/renderer/features/pilot_management/index.vue, src/renderer/features/pilot_management/mixins/activePilot.ts, src/renderer/features/pilot_management/store/index.ts, src/renderer/router.ts, src/renderer/ui/components/selectors/CCLicenseSelector.vue
This PR does away with the "ActivePilot" property in the pilot management store & instead encodes that information into the route URL for browser refresh compatibility.
To make the code less repetitive I also added an `activePilot` mixin under `pilot_management`, which automatically uses the `:pilotID` route param to grab the corresponding pilot object from the store and stores it as the `pilot` variable on the component.
Since this involved restructuring the routes a bit, a lot of router link paths had to be adjusted. I almost definitely missed some which will now lead to invalid paths, so keep an eye out.
=> Persist active pilot

src/renderer/io/Data.ts, src/renderer/io/ExtLog.ts, src/renderer/io/ImageManagement.ts, src/renderer/io/Startup.ts
I didn't take into account fresh installs with no %appdata%/compcon/data directory when I first wrote the Data module. This PR ensures it exists before trying to do anything with it.
Also fixes the default image dirs not getting created properly.
=> Ensure data and image dirs exist

src/renderer/features/_shared/classes/Loadout.ts
Add to more ordinal name values for Loadouts, based on wikipedia: https://en.wikipedia.org/wiki/Ordinal_numeral
So now it works up to twelve loadouts.
=> add two more ordinal values for loadouts.

src/App.vue, src/features/pilot_management/New/index.vue, src/ui/GlobalConfirm.vue
- Adds a confirm dialog that can be called from any component with `this.$confirm(...)` (returns a boolean promise)
- Adds a navigation guard for the pilot wizard that warns the user their in-progress pilot will be lost.
=> Add confirmation dialog when leaving pilot wizard

src/ui/components/panels/loadout/mech_loadout/components/_SlotCardBase.vue, src/ui/components/panels/loadout/mech_loadout/components/mount/weapon/_WeaponSlotCard.vue
In Active Mode, empty weapon slots let you select a weapon by clicking on the "EMPTY" text. Bit of an edge case since you should never be in a mission with empty weapon slots, but might as well take care of it
=> Fix empty slots allowing selection in Active Mode

src/features/pilot_management/New/pages/ConfirmPage.vue, src/ui/components/selectors/CCMechSkillsSelector.vue, src/ui/components/selectors/CCTalentSelector.vue, src/ui/components/selectors/components/_TalentSelectItem.vue
- Fixes bug where the talent selector allowed for selecting talents past
maximum. Also cleans up repeated code in CCTalentSelector and _TalentSelectItem.
- Stepper content in ConfirmPage was using a nonexistent canContinue value
for its complete prop. Change it to pilotReady.
- Makes it so CCMechSkillsSelector scrolls to bottom of the screen once
all selections have been made, like other selectors do.
=> More pilot wizard fixes

src/classes/ContentPack.ts, src/classes/Manufacturer.ts, src/classes/Tag.ts, src/features/compendium/store/index.ts, src/features/main_menu/_components/CCLog.vue, src/features/nav/pages/ExtraContent/PackInstall.vue, src/interface.ts, src/io/ContentPackParser.ts, src/schema.ts, src/ui/components/selectors/CCCoreBonusSelector.vue
- **Refactor(homebrew):** Use a @Brewable decorator for properties on the compendium store that
take items from content packs. Also fixes several bugs (I think) caused by using `private` inside vuex-module-decorator modules
- **Feat(homebrew):** Generates homebrew item IDs if they are not defined in the item. Also removes IDs from the schema to avoid unneeded complexity for end users
See commits for other changes
=> Homebrew fixes

src/classes/License.ts, src/classes/LicensedItem.ts, src/classes/Manufacturer.ts, src/classes/pilot/CoreBonus.ts, src/features/compendium/Views/CoreBonuses.vue, src/features/compendium/Views/Licenses.vue, src/features/compendium/Views/Manufacturers.vue, src/io/ContentPackParser.ts, src/schema.ts, src/ui/components/selectors/CCCoreBonusSelector.vue
⚠️⚠️⚠️**DO NOT PULL UNTIL ERANZIEL'S LATEST CHANGES ARE PULLED INTO LANCER-DATA**⚠️⚠️⚠️
Removes the `Manufacturer.Short` property as we are going back to using manufacturer acronyms for their IDs; changes all references to `Manufacturer.Short` to `Manufacturer.ID`. Also adjusts homebrew parsing & schemas to account for the changes.
=> Adjust manufacturer handling code to data changes

src/classes/pilot/Pilot.ts, src/features/pilot_management/ActiveSheet/index.vue
Counters were failing to load due to trying to pull from nonexistant
weapon mods
=> Fix counters in Active Mode

src/features/nav/index.vue, src/features/pilot_management/ActiveSheet/index.vue, src/features/pilot_management/ActiveSheet/layout/CountersBlock.vue, src/features/pilot_management/PilotSheet/components/PilotHeader.vue, src/features/pilot_management/PilotSheet/index.vue, src/features/pilot_management/PilotSheet/sections/info/components/AppearanceBlock.vue, src/features/pilot_management/PilotSheet/sections/info/components/HistoryBlock.vue, src/features/pilot_management/PilotSheet/sections/info/components/IdentBlock.vue, src/features/pilot_management/PilotSheet/sections/info/components/ImageBlock.vue, src/features/pilot_management/PilotSheet/sections/info/components/NotesBlock.vue, src/features/pilot_management/mixins/activePilot.ts, src/util/vueMixins.ts
Adds util/vueMixins.ts utility function to apply mixins to components type-safely while still using the Vue object syntax. 
Main benefit is getting proper type info/no errors when using the activePilot mixin in components that haven't been refactored to class-style components.
=> Add mixin util for object-pattern components

src/classes/Counter.spec.ts, src/classes/Counter.ts, src/classes/enums.ts, src/classes/mech/MechLoadout.ts, src/classes/pilot/Pilot.ts, src/classes/pilot/reserves/Reserve.ts, src/features/pilot_management/ActiveSheet/components/Counter.vue.spec.ts, src/features/pilot_management/ActiveSheet/turn/Downtime/BuyTime.vue, src/features/pilot_management/ActiveSheet/turn/Downtime/DamnDrink.vue, src/features/pilot_management/ActiveSheet/turn/Downtime/DowntimeManager.vue, src/features/pilot_management/ActiveSheet/turn/Downtime/DtAction.vue, src/features/pilot_management/ActiveSheet/turn/Downtime/GatherInformation.vue, src/features/pilot_management/ActiveSheet/turn/Downtime/GetConnected.vue, src/features/pilot_management/ActiveSheet/turn/Downtime/GetCreative.vue, src/features/pilot_management/ActiveSheet/turn/Downtime/GetFocused.vue, src/features/pilot_management/ActiveSheet/turn/Downtime/GetOrganized.vue, src/features/pilot_management/ActiveSheet/turn/Downtime/ReserveSelector.vue, src/features/pilot_management/ActiveSheet/turn/Downtime/ScroungeBarter.vue, src/features/pilot_management/ActiveSheet/turn/Mission/TurnManager.vue, src/features/pilot_management/ActiveSheet/turn/Mission/components/ActionButton.vue, src/features/pilot_management/PilotSheet/sections/mech/sections/attributes/index.vue, src/features/pilot_management/Print/MechPrint.vue, src/ui/components/CCStatusSelect.vue, src/ui/components/items/CCReserveItem.vue, src/ui/components/selectors/CCReserveSelector.vue, src/ui/components/selectors/components/_CustomReservePanel.vue, src/ui/theme.ts
Updates to Reserves and Downtime actions to account for changes in lancer-data.
Also includes fixes for issues on the V2 spreadsheet:
* Line 78, Lesson of Shaping not allowing 2 AI.
* Line 84, Prototype Weapon and FRG adding a nameless license to loadout requirements.
* Line 100, Status/condition tool tips in active mode not using html formatting.
* Line 103, Size 1/2 icons missing in active mode (also fixed for printed mech sheets).
=> Data updates and minor fixes

src/mixins/getColor.ts, src/ui/components/CCBtn.vue, src/ui/components/CCComboSelect.vue, src/ui/components/CCDamageElement.vue, src/ui/components/CCDialog.vue, src/ui/components/CCExtendedTag.vue, src/ui/components/CCGmHeader.vue, src/ui/components/CCItemUses.vue, src/ui/components/CCMajorBtn.vue, src/ui/components/CCMechStatusAlert.vue, src/ui/components/CCNotification.vue, src/ui/components/CCPopup.vue, src/ui/components/CCRangeElement.vue, src/ui/components/CCRating.vue, src/ui/components/CCShortStringEditor.vue, src/ui/components/CCSimpleSelect.vue, src/ui/components/CCSlashes.vue, src/ui/components/CCSoloDialog.vue, src/ui/components/CCStatblockPanel.vue, src/ui/components/CCStatusSelect.vue, src/ui/components/CCStepperContent.vue, src/ui/components/CCStringEdit.vue, src/ui/components/CCTag.vue, src/ui/components/CCTags.vue, src/ui/components/CCTickBar.vue, src/ui/components/CCTitle.vue, src/ui/components/CCTitlebar.vue, src/ui/components/CCTitledPanel.vue, src/ui/components/CCTooltip.vue, tsconfig.json
First batch of component refactors for #514, covering the basic /ui/components/* elements. 
A few obvious typing improvements have been made, but they could use additional validators, and some might benefit from further refactoring of props and prop usage (prop usage is mostly untouched in this PR).
=> Refactor base CC styled building block components to use VCC & VPD

src/classes/mech/Mech.ts, src/features/pilot_management/ActiveSheet/layout/MechBlock.vue, src/ui/components/CCTickBar.vue, src/util/sleep.ts
Currently, the logic for rolling over HP and heat and deducting structure/stress points accordingly is handled on the UI side inside the Vue components. This PR removes that logic from `CCTickbar` and `MechBlock` and adds it to the `Mech` class. In `MechBlock`, we instead use Vue watchers on the current structure and stress to pop up the appropriate roll table.
The most obvious benefit, aside from keeping business logic out of the UI, is that the stress/structure rollover (& accompanying roll table popups) are now triggered by any structure loss no matter what, rather than only ones caused by CCTickBar.
Closes #555. Should also consider closing #561 - rxJS might actually be overkill, but we should think it over.
=> Refactor hp/heat rollover out of Vue and into Mech class

src/classes/pilot/Pilot.ts, src/features/nav/pages/Options.vue, src/features/pilot_management/PilotSheet/components/CloudDialog.vue, src/features/pilot_management/PilotSheet/sections/info/components/IdentBlock.vue, src/features/pilot_management/Roster/components/add_panels/CloudImport.vue
Allows the user to edit their User ID, as well as edit the Cloud ID in the Pilot Dossier view. This allows a user to essentially claim ownership of a cloud save from multiple computers if they enter the same User ID on all of them.
In order for this to work, the cloud import was refactored to retain the pilot's cloud ID and cloud owner ID if the owner ID matches the user ID.
This also fixes a couple bugs to do with `Pilot.CloudOwnerID`. It was not set before uploading a pilot to the cloud initially, so currently all new cloud saves have no associated owner ID.
=> Editable UserID to allow cloud import ownership

src/features/main_menu/_components/MainTitle.vue, src/features/nav/index.vue, src/features/nav/pages/About.vue, src/io/BulkData.ts, src/main.ts, src/shims/shims-vue.d.ts, webpack.config.js
Generates a version string, which will be either: the tag on a (full release) Travis build, the commit ref on a Netlify (nightly/preview) build, or otherwise "Unknown".
Also adds the package.json version to the LANCER CORE version.
Resolves #483.
=> Generate version string based on environment

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md, .travis.yml, src/classes/mech/MechLoadout.ts
Fix #585.
Add integrated systems and weapon mods to the results of `MechLoadout.Equipment` so that they get checked for AI tags as well.
<strong>Note:</strong> The Technophile 3 AI currently doesn't have the bonus AI tag, so it will disallow other AIs until lancer-data is updated.
=> AI Counting Fix

src/classes/npc/NpcFeature.ts, src/classes/npc/NpcSystem.ts, src/ui/components/cards/_NpcTechCard.vue, src/ui/components/cards/_NpcWeaponCard.vue, src/ui/components/cards/npc/cards/_TechCard.vue, src/ui/components/cards/npc/cards/_TraitCard.vue, src/ui/components/cards/npc/cards/_WeaponCard.vue
Updates to NPC feature cards. 
Fixes #575, #576, #588.
Displays difficulty instead of "+-X Accuracy", added glyphs, made attack bonus/accuracy display order consistent between weapons and tech, added weapon type to compact cards.
Moves tag handling into the base NPCFeature class, since all types of features can have tags. Display tags on trait cards.
=> NPC feature card updates

src/classes/pilot/Pilot.ts, src/features/pilot_management/Roster/components/add_panels/CloudImport.vue
Cloud loading was broken, presumably using old code. Has been fixed.
Do not clear the cloud ID on cloud imported pilots, so that GM's/other players can use the quick sync function to pull updates. Also set the cloud ID on the imported pilot if it's missing (which will be the case after first upload).
#598
=> Cloud Sync Fixes

src/features/pilot_management/PilotSheet/sections/info/components/AppearanceBlock.vue, src/features/pilot_management/PilotSheet/sections/info/components/HistoryBlock.vue, src/ui/style/typography.css
Adds the `white-space: pre-wrap` style to the pilot biography & appearance blocks so that they preserve user line breaks. Bit of a bandaid while we implement #606
=> Show linebreaks in pilot biography & appearance blocks

.cz-config.js, .github/CODEOWNERS, build_scripts/release.sh, package.json, yarn.lock
- Replaces Commitizen plugin with [**cz-customizable**](https://github.com/leonardoanalista/cz-customizable), which adds the ability to set predefined scopes (& sets a few). Still `yarn commit`
- Remove standard-version, instead use a custom release script using standard-changelog, which allows for arbitrary version numbers. `yarn release` now requires an argument e.g. `yarn release 2.0.3`
=> Commitizen & release tweaks

src/ui/components/selectors/CCTalentSelector.vue
As per Tom, this is only enforced for LL0 characters - respeccing allows for 2 talents at LL1+
Closes #394
=> Remove warning for less than 3 talents after LL0

src/classes/npc/Npc.ts, src/classes/npc/NpcClassStats.ts, src/classes/npc/NpcFeature.ts, src/classes/npc/NpcReaction.ts, src/classes/npc/NpcSystem.ts, src/classes/npc/NpcTech.ts, src/classes/npc/NpcTrait.ts, src/classes/npc/NpcWeapon.ts, src/features/encounters/npc/new/index.vue, src/ui/components/cards/npc/cards/_ReactionCard.vue, src/ui/components/cards/npc/cards/_SystemCard.vue, src/ui/components/cards/npc/cards/_TraitCard.vue, src/ui/theme.ts
Implements functionality for the new optional "overrides" prop of NPC features. Overridden stats are still able to be manually modified when custom tier is selected.
Closes #631 
Bug fix. Should be self-contained.
=> NPC Stat Overrides

README.md
Instructions for building electron target incorrect. Changed target to electron:build from build:electron.
=> Correction to Building instructions for Electron

build_scripts/release.sh
This PR makes the `yarn release` script push its changes/tag to the remote to trigger a build, but not without asking the user for confirmation & rolling back its changes if it's cancelled.
=> add confirm & autopush to release process

src/features/pilot_management/PilotSheet/components/PilotEditMenu.vue, src/features/pilot_management/PilotSheet/components/PilotNav.vue, src/features/pilot_management/Roster/components/PilotListItem.vue, src/features/pilot_management/Roster/index.vue
Pulled out the function menu (gear icon) on the pilot sheet so it could be reused in the list items for the roster. Used there.
removed the `unskew` class from many of the menu items and just applied it to the entire menu in `PilotNav.vue` This was done because the gear menu is now shared with two types of menus, one that uses `skew` to achieve the clipped effect, and one that uses `clip-path` to achieve a similar affect. I attempted to make them use the same method, but it proved to be too difficult.
#533 
=> Add pilot menu to roster items

src/features/pilot_management/ActiveSheet/layout/CountersBlock.vue
The Custom Counter delete button was not properly pointing at the ID of the counter to be deleted in its code, so the function defaulted to deleting the latest counter created.
=> Fix custom counter delete button not deleting correct counter

src/classes/effects/ItemEffect.ts, src/classes/effects/ProfileEffect.ts
Fixes a few small issues which prevented tags from displaying on alternate weapon profiles. 
Closes #691.
=> Tag display on alternate weapon profiles

src/App.vue, src/classes/Interfaces.d.ts, src/features/main_menu/index.vue, src/features/nav/index.vue, src/features/nav/pages/Options/Log.vue, src/features/nav/pages/Options/Settings.vue, src/features/nav/pages/Options/index.vue, src/features/nav/store/index.ts, src/main.ts, src/ui/GlobalNotifier.vue
Adds error notifications using the global notifier. Adds a new tab under Options that keeps logged errors (lost on refresh for now).
It will catch everything both inside and outside Vue - unfortunately vuex-module-decorator catches all errors and doesn't give a way to add a custom error handler - the only way to get around it is to manually add a `rawError` prop to every action decorator. They might fix this in the future, if not we might want to do this as tedious and ugly as it would be, since store errors are pretty important.
Would like it so that clicking on the notification sends you to the error logging page, but for that I'll need to globalize the options dialog.
=> Add error notifications and logging

src/classes/npc/Npc.ts
If an NPC mech takes HP damage then they have available HP, the amount HP remaining after the structure roll was being improperly calculated.  Thanks to @aritsune for [pointing out exactly where to fix](https://github.com/massif-press/compcon/issues/803#issuecomment-618584004).  I also went and [verified that this is being properly set for PC mechs](https://github.com/massif-press/compcon/blob/master/src/classes/mech/Mech.ts#L401).
#803
=> fix(Mission Runner): Ensure remaining HP is calculated correctly after structure roll

src/ui/components/cards/CCItemCard.vue
I ran into an error in the NPC builder when adding features in using the selector split view, encountering sporadic `t.item.Damage is not a function` error toasts when selecting features in the left column of the selector.  I managed to narrow it down to a repro:
1) Create a new NPC (I went with Berserker, where I knew I had run into this error before)
2) Select that new NPC in the NPC Roster
3) Click the `Add Feature` button
4) Click on a weapon feature (For the Berserker, `Nail Gun` and `Harpoon Cannon` fit his criteria)
5) Observe a correctly rendered NpcWeapon card with the weapon's stats
6) Click on an item feature (For the Berserker, `Juggernaut`, `Retribution`, and `Superhot` fit this criteria)
7) Observe a correctly rendered NpcItem card with the system's stats
8) No error toast …
=> fix(Item Card): Make sure item card re-imports correct component when this.item updates

src/features/encounters/encounter/components/NpcSelector.vue
Scrolling was broken when clicking the name of an NPC selector, but only in the Mission Runner and not encounter builder.  Turns out in the Mission Runner, there were TWO open/active dialogs ([`NpcSelector` was in a `CcSoloDialog` inside of `ReinforcementsModal`](https://github.com/massif-press/compcon/blob/master/src/features/encounters/mission/runner/components/ReinforcementsModal.vue#L98-L100), but [`ReinforcementsModal` was in a `CcSoloDialog` inside of `EncounterNav`](https://github.com/massif-press/compcon/blob/master/src/features/encounters/mission/runner/components/EncounterNav.vue#L116-L124)!) and when passing a selector instead of an element to `$vuetify.goTo`'s options object it uses the first one found in the document, which was NOT the one we intended.
I updated this to …
=> fix(Mission Runner): Restore scrolling in NPC selector for reinforcements

src/features/encounters/encounter/components/NpcSelector.vue
Vuetify.goTo was running into issues when multiple `NpcSelector` components were rendered on a page at once.  We were giving a "unique" ID to each container element for the NPC list, but if there were multiple `NpcSelector` components on the page (such as in the Encounter Builder), these IDs were getting duplicated and the browser was getting them confused.  Adding the `NpcSelector` components auto-generated uid to the NPC element ID solved this.  I also went back and tested in the Mission Runner reinforcements modal and it still works there as well.
#816
=> fix(Encounter Builder): Restore scrolling when multiple NPC selectors have been active on page

src/classes/Statblock.ts
The NPC statblocks we generated had some issues in formatting, specifically around NPC templates and features.  I touched up the whitespace and applied the `linebreak()` function we're using on PC statblocks for NPC features.
```
// New ACE //
ACEVETERAN ELITE, Tier 1 Mech
[ STATS ]
H: -2 | A: 3 | S: 1 | E: 0
STRUCT: 3 | ARMOR: 0 | HP: 10
STRESS: 3 | HEATCAP: 8 | SPD: 5
SAVE: 10 | EVADE: 12 | EDEF: 8
SENS: 10 | SIZE: 1 | ACT: 2
[ FEATURES ]
SSC FLIGHT SYSTEM (I)
MISSILE LAUNCHER (I)BARREL ROLL (I)BOMBING BAY (I)
CHAFF LAUNCHERS (I)RAPID RESPONSE (I)STRAFE (I)
MISSILE SWARM (I)REINFORCED (I)VETERANCY (I)
VETERAN TRAITS (I)HACKER (I)PARTING GIFT (I)
SHOCK ARMOR (I)SELF REPAIR (I)INSULATED (I)
REINFORCED (I)READY AND WAITING (I)CAREER SOLDIER (I)
SPECIALIST KIT (I)
```
```
// New ACE //
ACE …
```
=> fix(NPC Roster): Align NPC statblock format with PC Mech statblock format

src/classes/Interfaces.d.ts, src/classes/pilot/CustomSkill.ts, src/classes/pilot/Pilot.ts, src/classes/pilot/PilotSkill.ts, src/ui/components/selectors/components/_AddCustomSkill.vue
Adds the detail field to custom skill triggers, bringing them in-line with built-in skill triggers.
This allows users to provide a terse description of their custom triggers, and a more detailed
explanation for the fold-out view in both the narrative profile and active mode views.
Closes #903
=> feat(Pilot Sheet): adds the detail field to custom skill triggers

src/ui/components/cards/npc/cards/_ReactionCard.vue
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Simple change, only display 'TRIGGER' label on NPC reactions that actually have triggers, in response to Issue #915 
`#915`
- [ X] Bug fix (non-breaking change which fixes an issue)
=> TRIGGER label will only appear if reaction actually has a trigger

src/features/compendium/Views/PilotGear.vue
Pilot Gear compendium was not showing Uses.
Uses is a state variable, and is not set if the object isn't instantiated.
however, MaxUses is Constant, and is the data we need to show anyway.
`#938`
- [x ] Bug fix (non-breaking change which fixes an issue)
=> Changed Gear uses on Compendium to show MaxUses

src/ui/components/selectors/CCImageSelector.vue
Image uploader on Electron was erroring when opening the native dialog.
This was because the `electron.remote.showOpenDialog()` function is Async, and was not being awaited.
So electron would open the dialog and continue executing. resulting in the path being undefined.
awaiting the function fixes the issue.
`#950`
- [ X] Bug fix (non-breaking change which fixes an issue)
=> Fixed image uploader not being awaited

src/features/pilot_management/PilotSheet/components/PilotHeader.vue
Small styling change, spacing on the Pilot Sheet Header was a little odd
=> Fixed a little spacing on the pilot header

src/features/compendium/Views/Systems.vue
Added the ability to sort Systems by License Level, by adding a License Level column.
This may not be the best way to do this?
its possible this sorting functionality could be added to the existing License column? please advise
Also, renamed the component class from `Weapons` to `Systems`
Suspect this was a copy paste error, didn't break anything, as all imports were using the default import 
#929
=> feat(Compendium): add License Level column to Systems table

src/features/encounters/mission/runner/components/NpcCard.vue
When a large Image is added to an NPC, when that npc is viewed on the Mission runner, it expands to its original size, taking up huge amounts of space and pushing the other controls down the page.
I have added a limit of the size the image can take on the Encounter screen to 50% Viewport size,
bug mentioned on discord
=> Fixed Npc image being massive and pushing controls really far down

src/ui/components/panels/loadout/active_loadout/components/_WeaponAttack.vue
This fixes a blanket issue where mods that grant the overkill tag are not counted for automatic overkill tracking in active mode.
This is the generic half of the fix for #1424 the specific fix to apply the overkill tag on the paracausal mod can be found [in the lancer-data PRs](https://github.com/massif-press/lancer-data/pull/149)
`#1424`
=> Add active mode check for overkill granted by a mod

CONTRIBUTORS.md, package.json, webpack.config.js, webpack_config/webpack.dev-public.config.js
Adds a new yarn build target to allow dev builds to be visible outside of localhost of the building machine. This is useful for situations where the machine building cannot be used to view the site. ex. Headless build servers.
=> Dev builds visible on LAN

src/classes/dice/DiceRoller.ts, src/ui/components/CCDiceMenu.vue, src/ui/components/panels/loadout/active_loadout/components/_PilotAttack.vue, src/ui/components/panels/loadout/active_loadout/components/_WeaponAttack.vue
These changes overhaul how critical hits and overkill heat is calculated and displayed. The new method is more accurate for critical hit damage, and ( subjectively ) displays roll output more clearly. I will provide a summary of the algorithm changes, with screenshots, in the comments.
It also now accounts for overkill with bonus damage as well.
`#1404`
=> Critical Hit / Overkill damage overhaul

src/classes/mech/Mech.ts, src/classes/pilot/Pilot.ts
In looking at adding counters for Brutal LV3 and the Black ICE Module, I noticed that the ZF4 Solidcore counter was already present. In my testing neither the Solidcore or the Black ICE Module counters displayed. These changes fix that such that counters provided by equipment or frames are displayed in active mode.
#1409 
#1410 
#1411
=> fix(Active Mode): allow counters provided by the mech to be displayed

src/classes/mech/Mech.ts, src/ui/components/tables/CCStressTable.vue
These changes fix issue #1412 such that rolling a "Meltdown" with only 1 stress remaining now causes an immediate "Critical Reactor" state.
This also fixes an unlisted issue where going down to 0 stress did not cause an immediate "Critical Reactor" state at all. Please see comments for more information.
`#1412`
=> Correct Critical Reactor behavior at 1 and 0 Stress

src/features/pilot_management/PilotSheet/components/ExportDialog.vue
* The `ExportDialog` was not using the `ShareCode` getter from the `ICloudSyncable` `Pilot` which was preventing users from getting a usable share code string -- instead all they'd get is the uid for their pilot.
* Note that in the "Sheet View" for the actual pilot page does seem to use the `ShareCode` so there is currently a workaround for obtaining a usable vault code.
=> Fixed the `ExportDialog` to print the real vault ShareCode

src/classes/Action.ts, src/ui/components/panels/loadout/active_loadout/CCCombatDialog.vue, src/ui/components/panels/loadout/active_loadout/components/_ActionActivationButtons.vue, src/ui/components/panels/loadout/active_loadout/components/_TechAttack.vue, src/ui/components/panels/loadout/active_loadout/dialogs/action/_ActionDialogBase.vue, src/ui/components/panels/loadout/active_loadout/dialogs/action/_FullTechDialog.vue, src/ui/components/panels/loadout/active_loadout/dialogs/action/_InvadeDialog.vue, src/ui/components/panels/loadout/active_loadout/dialogs/action/_ItemActionDialog.vue
Closes #1317
These changes utilize a new field in the IActionData struct to bring up the roll menu when activating something ( system, talent, ....) that causes a tech attack.
`#1317`
=> feat(Active Mode): add support for rolling Tech Attacks other than Invade

src/ui/components/panels/loadout/pilot_loadout/_PLWeaponCard.vue
Fixes missing equip button for Pilot Weapon list view using the same fix as the pilot gear list for issue #1495.
`#1529`
=> fix(Pilot Sheet): fix missing pilot weapon equip button in list mode

src/ui/components/cards/npc/cards/_ItemMenu.vue
This fix points the getter/setter of an NPC Item to the correct location to properly edit the item's Name and Description & save them.  Found that the `cc-string-edit-dialog` was pointed at an NpcFeature object, which a) lacks a Name setter and b) lacks a Description field.  This change should point the dialog box to the correct object.
`#1505`
=> fix(NPC Roster): fix editing NPC Feature Names & Descriptions

src/classes/mech/Mount.ts, src/ui/components/panels/loadout/mech_loadout/components/mount/_MountBlock.vue
These changes add tooltips for weapon mounts that display the available mount fittings for the mount type.
I went with a "hardcoded" implementation after trying to implement this using `Rules.MountFittings` and `Mount.slots` and `Mount.extra`, but I don't think it's possible to use the existing data to handle cases like Main/Aux or Flexible mounts correctly. IMO the easiest way to represent this is to just hard-code string representations of the mount fittings, but I'm open to reworking this if a more flexible implementation is desired.
#1541
=> Add tooltips for weapon mounts

src/ui/components/selectors/CCSkillSelector.vue, src/ui/components/selectors/components/_AddCustomSkill.vue
This change disables the `add-custom-skill` button when the pilot cannot select more skills.  Using `Pilot.IsMissingSkills` instead of `Pilot.CanAddSkill` since there's no pre-existing skill to search or compare against when adding a new custom skill.
Closes #1580
=> fix(Pilot Sheet): disable custom skill creation when 0 skills remaining

src/features/compendium/Views/Frames.vue, src/features/compendium/Views/Systems.vue, src/features/compendium/Views/Weapons.vue
This PR changes the default sort of compendium entries for Mech-related items (frames, systems, and weapons) to book order of the manufacturers, for consistency with the Manufacturers, Licenses, and Core Bonuses pages.
Closes #1496
=> feat(Compendium): sort Mech frames/weapons/systems in book order

src/ui/components/selectors/CCImageSelectorWeb.vue
With this fix, in the image selector: If the selected image's source is a URL, it uses the image URL for displaying the image.
Prior to this fix, the selected image would only have its basename stored as a "local" filename, which appended `static/img/(mech/pilot)` to the file's basename.  This led to broken references for frames that lacked a corresponding local static image file, e.g. Wallflower frames and Long Rim frames with alternative naming schemes (e.g. `lich_off.png` remote vs. `mf_lich.png` local).
I also created a [sibling PR](https://github.com/massif-press/long-rim-data/pull/10) that addresses consistency in frame `image_url` naming conventions in the Long Rim data pack.
Closes #1439
=> fix(Mech Sheet): frames with webhosted images use the webhost address

src/features/main_menu/_components/login/SignedIn.vue, src/features/nav/pages/Options/Settings.vue, src/features/pilot_management/store/index.ts, src/user/index.ts, src/user/store/index.ts
Adds a user toggle to sync data when the user changes their COMP/CON theme.  When enabled, theme should sync immediately with the cloud.
UPDATE: While setting up the `onThemeChange` toggle condition, I noticed several sync conditions were routed on the wrong condition name or SyncFrequency property.  This update fixes most of them; still todo are:
1. `onPilotLevel` lacks a cloudsync call
2. `onAppExit` lacks any sort of implementation.  
These will need additional work to fix, but would be better off in a new PR.  Current PR state is ready for review.
Closes #1450
=> fix(options): adds option to sync on Theme change (default true)

src/ui/components/cards/_FrameCard.vue, src/ui/components/cards/_MechSystemCard.vue, src/ui/components/cards/_MechWeaponCard.vue, src/ui/components/cards/_NpcSystemCard.vue, src/ui/components/cards/_NpcTechCard.vue, src/ui/components/cards/_NpcTraitCard.vue, src/ui/components/cards/_NpcWeaponCard.vue, src/ui/components/cards/_WeaponModCard.vue
Closes #1502
Do we need this info for talents and NPC features?
This displays originating LCP information for various pieces of content
`#1502`
=> feat(Homebrew Content): display original LCP for player mech items

src/classes/Deployable.ts, src/classes/mech/Mech.ts, src/classes/pilot/Pilot.ts
Changes current HP tracking to use a "missing HP" model so it will easily calculate adjustments to Max HP both immediately after pilot/frame/deployable creation, as well as scale Current HP to match increases in Max HP (e.g. if hp is 5/10 and Max HP increases by +2, new HP value is 7/12).
Closes #1569
=> fix(Pilot Sheet/Mech Sheet): initializes Pilot, Mech, & Deployable HPs to final Max

src/classes/mech/MechWeapon.ts, src/ui/components/CCExtendedTag.vue
We now provide the list of hombrew pack-specific tags to the weapon profile constructor.
Closes #1482 
`#1482`
=> fix(Compendium): correctly use homebrew tags for weapon profiles

src/classes/pilot/Pilot.ts, src/ui/components/selectors/CCSkillSelector.vue, src/ui/components/selectors/CCTalentSelector.vue
This PR fixes the Talent scrolling on click during new pilot creation, and also applies the same scrolling to skill trigger selection.  Additional sorting of skills was also included.
To be honest, this PR started with an attempt at sorting a Pilot's skills upon addition/removal/setting, and evolved into applying a `$vuetify.goTo` to the skill trigger selections, which evolved into finding and fixing issue #1566.
Closes #1566, addresses one part of #917 within the scope of Pilot Management
=> fix(Pilot Sheet): fix Talent scroll on click for new pilots

src/classes/pilot/Pilot.ts
Followed pattern of bonus reserve License to increase the maximum number of skill trigger assignments available to a pilot.  Bonus skill point will be awarded for every instance of the 'Skill Focus' Reserve.
Closes #1549
=> fix(Pilot Sheet): skill Focus reserve grants bonus skill triggers

webpack_config/webpack.dev-public.config.js
Previously, the dev-public target, which provides the dev server to addresses other than `localhost` was not providing an SSL connection. This was preventing LCP files from being uploaded to the dev-public site.
( This is working on the `dev` target currently because browsers currently treat 'localhost' addresses as trusted, just like SSL sites )
=> build: allow public dev server to use SSL

src/ui/components/selectors/CCBackgroundSelector.vue
A typo in the BackgroundSelector led to undefined Background IDs. This prevented the Vuetify GoTo function from scrolling on click. The amended HTML now properly pulls the Background IDs.
Closes #1561
=> fix(Pilot Sheet): goTo Background description on click fixed

src/ui/components/Talent/components/_TalentSmall.vue, src/ui/components/Talent/components/_TalentTerse.vue
Reorients the _TalentSmall.vue and _TalentTerse.vue components so the hoverable talent tooltip is offset above the talent icon.
Previously oriented to bottom, leading to overlap with the Pilot navbar.
Closes #1560
=> fix(Pilot Sheet): top Offset-Y Talent card popup in pilot Tac Profile

src/features/pilot_management/Roster/components/add_panels/VaultImport.vue
Closes #1606
This change converts input vault codes to lowercase before requesting them in AWS.
`#1606`
=> fix(vault): handle imported vault codes in a case insensitive manner

src/classes/Action.ts, src/classes/Bonus.ts, src/classes/Damage.ts, src/classes/Range.ts, src/classes/Synergy.ts, src/classes/pilot/Pilot.ts, src/classes/pilot/reserves/Reserve.ts, src/ui/components/panels/loadout/active_loadout/dialogs/downtime/_BuySomeTime.vue, src/ui/components/panels/loadout/active_loadout/dialogs/downtime/_GatherInformation.vue, src/ui/components/panels/loadout/active_loadout/dialogs/downtime/_GetADamnDrink.vue, src/ui/components/panels/loadout/active_loadout/dialogs/downtime/_GetConnected.vue, src/ui/components/panels/loadout/active_loadout/dialogs/downtime/_GetCreative.vue, src/ui/components/panels/loadout/active_loadout/dialogs/downtime/_GetFocused.vue, src/ui/components/panels/loadout/active_loadout/dialogs/downtime/_GetOrganized.vue, src/ui/components/panels/loadout/active_loadout/dialogs/downtime/_PowerAtACost.vue, src/ui/components/panels/loadout/active_loadout/dialogs/downtime/_ScroungeAndBarter.vue
This PR started with fixing an issue introduced by #1564, and developed into realizing we don't actually store bonuses/actions/synergies/etc. for custom-made reserves (i.e., any stemming from Downtime Actions, *NOT* just the 'Custom Reserve' reserve).  Any bonuses, actions, synergies, etc. would only be available for the Reserves listed in `lancer-data`, as reserves with IDs matching those in `lancer-data` are retrieved fresh every time.  This PR aims to address the discrepancy, and hopefully will open the way to a wider variety of custom reserves.
Closes #1589
=> fix(Pilot Sheet): fix Skill Focus, setup custom reserve retrieval

src/ui/components/CCDiceMenu.vue, src/ui/components/panels/loadout/active_loadout/components/_PilotAttack.vue, src/ui/components/panels/loadout/active_loadout/components/_TechAttack.vue, src/ui/components/panels/loadout/active_loadout/components/_WeaponAttack.vue, src/ui/components/panels/loadout/active_loadout/dialogs/action/_GrappleDialog.vue, src/ui/components/panels/loadout/active_loadout/dialogs/action/_OverchargeDialog.vue, src/ui/components/panels/loadout/active_loadout/dialogs/action/_RamDialog.vue, src/ui/components/panels/loadout/active_loadout/dialogs/action/_SearchDialog.vue, src/ui/components/panels/loadout/active_loadout/dialogs/action/_SkillCheckDialog.vue
Closes #1551
This change will auto-populate rolls for Mech attacks and damage, Pilot attacks and damage, Mech tech attacks, Skill checks, Ram, Grapple, Search, and Overcharge.
This does NOT auto-roll bonus damage, that will still need to be done manually.
`#1551`
=> feat(Active Mode): auto-roll some dice when actions are selected

src/classes/mech/Mech.ts, src/classes/mech/MechEquipment.ts, src/classes/mech/MechSystem.ts, src/classes/mech/MechWeapon.ts, src/classes/mech/SystemMod.ts, src/classes/mech/WeaponMod.ts, src/classes/pilot/PilotEquipment.ts, src/ui/components/CCItemUses.vue, src/ui/components/panels/loadout/mech_loadout/components/_EquipmentHeader.vue
Use a "missing stat" approach similar to the HP changes in #1569 for similar statistics so that the "current" values scale with increases to the maximum values.  Most noticeable with Repair Cap due to Hull bonuses; Structure & Stress included in case respective bonuses are introduced.  Also performed similar scaling for Limited-use systems (though more of the math was on the Vue/HTML side), most noticeable on Prototype weapon.
Closes #1586
=> fix(Mech Sheet): scale stats with max stat increases

package.json, public/index.html, src/features/compendium/Views/Factions.vue, src/features/compendium/Views/Manufacturers.vue, src/features/nav/pages/ExtraContent/PacksDirectory.vue, src/ui/components/items/CCLogo.vue, yarn.lock
Loads large Manufacturer/Faction logo as a static img instead of a dynamic svg in the compendium. 
Incorporates [external-svg-loader](https://www.npmjs.com/package/external-svg-loader) for potential future use should content creators provide SVG references with CORS compatible with compcon.app.
Closes #1535
=> fix(Compendium): load static image for homebrew manufacturers

src/classes/pilot/Pilot.ts, src/ui/components/selectors/CCSkillSelector.vue, src/ui/components/selectors/components/_AddCustomSkill.vue
This change modifies the logic checking if a pilot can add a skill trigger so that LL0 pilots with extra skill points can select additional talents.  In addition, it modifies the approach to protecting from custom added triggers to simply use `Pilot.CanAddSkill()`, differing from the original fix in #1582.
Closes #1600
=> fix(Pilot Sheet): LL0 Pilots can select bonus skill triggers

src/features/pilot_management/PilotSheet/sections/mech/components/MechNav.vue
Closes #1597
Added tooltip text to the mech sheet nav buttons that was missing. 
`#1597`
=> fix(Mech Sheet): add tooltips to the Mech Sheet Nav bar buttons

src/classes/mech/ActiveState.ts, src/classes/pilot/Pilot.ts
Closes #1605
This adds a new field field to the ActiveState class and extends the "SyncIgnore" behavior from the Pilot class to provide a way for users who have synced another pilot to set a local active mech. This local active mech is ignored if the active mech is set and published by the owner of the pilot at a later date. 
This is useful to GM users who need an active mech on their player characters for the mission runner.
`#1605`
=> fix(Mission Runner): allow for overwriting active mech on synced pilot

src/features/pilot_management/New/pages/MechSkillsPage.vue, src/features/pilot_management/New/pages/SkillsPage.vue, src/features/pilot_management/New/pages/TalentsPage.vue, src/ui/components/selectors/CCSkillSelector.vue, src/ui/components/selectors/CCTalentSelector.vue
Fixes error where skill & talent scrolling were disabled for LL0 characters when directly modifying their skills/talents outside of character creation or leveling up.  Adds 'level-up' prop to the New Pilot skill, talent, & (vestigially, but for consistency) mech skill selectors to indicate the difference in HTML containers.
Closes #1609
=> fix(Pilot Sheet): enable scroll-on-click for LL0 pilots in Skill & Talents

src/features/pilot_management/Roster/components/add_panels/CloudImportOld.vue, src/features/pilot_management/Roster/components/add_panels/FileImport.vue, src/features/pilot_management/Roster/components/add_panels/ImportDialog.vue, src/features/pilot_management/Roster/components/add_panels/VaultImport.vue, src/features/pilot_management/Roster/index.vue, src/features/pilot_management/store/index.ts
This PR refines #1647 such that newly-imported pilots ~~import their group with them, and~~ are immediately visible. This PR also makes pilot sorting/reindexing more robust.  Finally, this PR changes the default display state for new groups to "visible", ~~and adds more detail to the Import Pilot message to include Pilot Group~~.
EDIT: Updated such that ~~newly-created and~~ imported pilots do NOT import their group, and are instead Ungrouped.  Removed Pilot Group from Import Pilot message.  Keeping the sorting/reindexing and the default display states, as I think they meaningfully add to the project.
EDIT 2: Moved the "ungrouping" to pilot imports only, so that cloned pilots retain the group of their original pilot (a feature that I feel will be more convenient than always sending a …
=> fix(Pilot Sheet): pilot imports ungrouped, immediately visible

src/classes/pilot/PilotArmor.ts, src/features/pilot_management/Print/PilotPrint.vue
Removes the Speed Bonus stat from PilotArmor, as it appears to be a deprecated statistic that will be accounted for within the armor's Speed stat calculation.  Removes reference to the stat from Print mode, and makes slight formatting adjustments for readability.
Closes  #1624
=> fix(Pilot Sheet): remove SpeedBonus stat from PilotArmor

src/classes/mech/MechEquipment.ts, src/classes/mech/MechWeapon.ts, src/classes/pilot/PilotEquipment.ts, src/ui/components/CCItemUses.vue, src/ui/components/panels/loadout/mech_loadout/components/_EquipmentHeader.vue
This fix rearranges the Serialization & Deserialization of MechWeapon's MaxUseOverride & total Uses so that Deserialization of Uses occurs *after* MaxUseOverride.  This is relevant since Uses is calculated based upon MaxUseOverride. Also includes minor refactors that will hopefully make the code more readable & maintainable.
Closes #1649
=> fix(Mech Sheet): prototype Weapon deserializes Uses after MaxOverride

src/classes/CompendiumItem.ts, src/classes/Deployable.ts, src/classes/Tag.ts, src/classes/mech/MechWeapon.ts, src/ui/components/panels/loadout/active_loadout/components/_WeaponAttack.vue
This PR properly casts ProfileHeatCost as a `number` object.  It also changes Item.Tags references in `_WeaponAttack.vue` to Item.ProfileTags, so weapon profile tags are properly applied in Active Mode.
Closes #1655
=> fix(Active Mode): cast Tag vals as numbers, use profile tags

src/classes/ContentPack.ts, src/classes/npc/NpcClass.ts, src/classes/npc/NpcFeature.ts, src/classes/npc/NpcReaction.ts, src/classes/npc/NpcSystem.ts, src/classes/npc/NpcTech.ts, src/classes/npc/NpcTemplate.ts, src/classes/npc/NpcTrait.ts, src/classes/npc/NpcWeapon.ts, src/features/compendium/Views/NpcTemplates.vue, src/features/encounters/npc/components/TemplateSelector.vue, src/features/encounters/npc/new/ClassCard.vue, src/ui/components/cards/_EquipmentCardBase.vue, src/ui/components/cards/_NpcReactionCard.vue, src/ui/components/cards/_PilotArmorCard.vue, src/ui/components/cards/_PilotGearCard.vue, src/ui/components/cards/_PilotWeaponCard.vue, src/ui/components/items/CCCoreBonusItem.vue
This change should display the origin ( if not originating from the Lancer CORE material, including the CORE Npc lcp ) for the following items:
Player Core Bonuses
Pilot Gear
Pilot Armor
Pilot Weapons
Npc Classes
Npc Features ( Systems, Weapons, Tech, Reactions )
Npc Templates
This should conclude the series of changes that I started a while ago.
=> Remaining LCP indicators

src/features/compendium/Views/Licenses.vue
This change increases visibility of the frame art in the License Compendium.  Prior to this,
expanding the viewable window led to a larger right-side cropping of the frame art.  While the
license banner loses some balance as a result, it will lead to fewer "weird" crops of the frames'
art.
NOTE: This PR was made primarily due to a somewhat unflattering crop of the Mourning Cloak's art in the License page of the Compendium.  If the previous style is desired, an alternative fix could be to mirror the Mourning Cloak's art so that its head is facing leftwards instead.  That said, the cropping issue could still affect other frames' art, regardless of where the frame creator positions the image in the banner.
Closes #1690
=> style(Compendium): prevent overcropping License frame art

src/classes/mech/Mount.ts
This change unequips the extra auxiliary weapon on a Flex mount when a Main weapon is equipped to the primary slot.  If the primary slot is empty, any equipped extra auxiliary weapon remains equipped and visible.  This primarily benefits any external user or application processing pilot data imported from Comp/Con (e.g. FoundryVTT-Lancer).
Closes #1692
=> fix(Mech Sheet): unequip Flex Aux Equips on Main Equip

src/classes/Statblock.ts, src/classes/mech/MechEquipment.ts, src/classes/mech/MechWeapon.ts, src/classes/pilot/PilotEquipment.ts, src/features/pilot_management/Print/MechPrint.vue, src/ui/components/CCItemUses.vue, src/ui/components/panels/loadout/active_loadout/CCCombatDialog.vue, src/ui/components/panels/loadout/mech_loadout/components/_EquipmentHeader.vue
This change retools how Max Uses and Total Limited Uses are calculated and presented in Active mode
to ensure that a mech has the correct number of limited uses at the start of a mission.  It changes
the logic behind Max Use Override so that bonuses must be manually included in the override. Lastly,
this includes a couple of other minor changes that polish some of the Limited Systems behaviors in
Active Mode.
Closes #1708
=> fix(Active Mode): limited uses initialize to correct maximum

src/classes/mech/ActiveState.ts, src/classes/pilot/Pilot.ts, src/features/encounters/mission/runner/PilotSelector.vue, src/features/pilot_management/ActiveSheet/components/DestroyedAlert.vue, src/features/pilot_management/ActiveSheet/layout/footers/NarrativeFooter.vue, src/features/pilot_management/New/pages/TemplatesPage.vue, src/features/pilot_management/PilotSheet/sections/hangar/components/MechCard.vue, src/features/pilot_management/PilotSheet/sections/hangar/components/MechListItem.vue
This change resets the active state self-destruct timer on any repairs performed.  It also creates a new ActiveState upon setting a new mech to Active.
It would probably not be unreasonable to move the Self Destruct Counter into an individual mech, either, and to reset it on repairs.  Please let me know if you think moving the Counter would be cleaner than what I currently have here.
Closes  #1728
=> fix(Active Mode): reset self-destruct counter on repair, mech change

src/features/main_menu/_components/login/SignedIn.vue, src/user/index.ts, src/user/store/index.ts
This change separates the "On App Load" and "On User Sign In" options into a "Load Frequency" category, indicating that when enabled, CompCon will automatically pull from the cloud when those events trigger.  This change also adds a "Cloud Load" button that manually pulls data from the cloud.  Lastly, this change modifies wording surrounding sync functions to clarify what is occurring during the sync (a "save" to the cloud, or a "load" from the cloud).
Closes #1726
=> feat(Cloud): settings for manually pulling data from cloud

src/features/compendium/Views/Reference.vue
This commit changes the "free action" Engineering check for a reactor melting down into a "full action" to reflect errata in the Lancer FAQ.  It also includes some minor typo fixes in the same page.
Closes #1748
=> fix(Compendium): fix typos in Structure and Stress references

src/features/pilot_management/PilotSheet/sections/mech/components/CoreItem.vue, src/ui/components/cards/frame/_FrameCoreSystemPanel.vue
This fix serves to temporarily hide the Duration chips from Core System descriptions due to inconsistent use of the duration tags causing confusion amongst users.  They will remain commented out until a more robust fix is implemented.  A more robust fix will involve modifying the logic behind assigning Core System durations, as well as adjusting CompCon's lexicon to cleave more closely to the Lancer Core Book (e.g. prefer using "Scene" over "Encounter").
Addresses #1736, but I would like to keep the issue open for tracking a future fix.
=> fix(Mech Sheet): temporarily hide duration chips for Core Systems

src/classes/Synergy.ts, src/classes/enums.ts
This feature adds an "All" enumeration to WeaponTypes that maps to `"???"`, and enables all
WeaponType synergies for that enumeration.  This is primariy in benefit to the Mimic Gun; hopefully
this won't negatively affect existing homebrews in the process.
Closes #1734
=> feat(Mech Sheet): enable all synergies for "???" type weapons

src/features/pilot_management/Print/BlankMechPrint.vue, src/features/pilot_management/Print/BlankPilotPrint.vue, src/features/pilot_management/Print/MechPrint.vue, src/features/pilot_management/Print/PilotPrint.vue
This change includes some redundant width settings for browsers that don't recognize `-webkit-fill-available`.  The unrecognized options are subsequently ignored, so we are safe to add redundant `width` settings.
Closes #1768
=> style(Pilot Sheet): fix number spacing over icons in Print mode

src/classes/pilot/Pilot.ts, src/features/pilot_management/PilotSheet/components/CloudManager.vue, src/features/pilot_management/PilotSheet/sections/info/components/CombatHistoryBlock.vue, src/features/pilot_management/PilotSheet/sections/info/components/ImageBlock.vue, src/features/pilot_management/PilotSheet/sections/info/index.vue
This change ensures persistent pilot combat stats between missions.  It adds a visible stat record under Pilot Combat Telemetry Record on the Dossier tab of Pilot Management.  This is an incredibly basic change; it could definitely stand to be improved upon in the future.
Closes #1765
=> feat(Pilot Sheet): add basic pilot stats to Dossier

src/features/pilot_management/New/index.vue, src/features/pilot_management/New/pages/ConfirmPage.vue
This fix enforces the Quickstart options on the confirm page, properly disabling the "Register Pilot" button when missing mandatory fields.
Closes #1762
=> fix(Pilot Sheet): block pilot registration when quickstart is off

src/features/pilot_management/Roster/components/PilotCard.vue, src/features/pilot_management/Roster/components/PilotListItem.vue, src/features/pilot_management/Roster/index.vue, src/features/pilot_management/store/index.ts
~~This is an initial commit for improving performance in the Pilot Roster.  It lays the groundwork for using nested Draggable components, utilizing the yet-unused `pilot_groups.json` for persisting Roster organization, and fixes autoscrolling issues (and drag-and-drop ghost issues in Chrome).  It is far from complete; PilotStore needs cleaned up to fit the new Group paradigm, the Pilot Groups object needs to be used directly in Draggable, and it should probably be load-tested to see if it can handle large lists of pilots.~~
UPDATE: 
This change refactors the way we organize the pilot roster, storing group configuration in `pilot_groups.json`.  This file tracks the Group Name, Hidden status, and list of Pilot IDs of pilots in the group.  The groups themselves have become draggable, and …
=> fix(Pilot Sheet): Refactor Pilot groups for performance & roster improvements

src/features/pilot_management/ActiveSheet/layout/footers/CombatFooter.vue
This fix removes the burn check from the "Start Round X" button, since Burn is only checked at the end of a player's turn.
#1774
=> fix(Active Mode): remove burn check from Active Mode End Round

src/classes/utility/ItemFilter.ts
This PR changes how the ItemFilter filters on tags.  The current Tag filter includes every weapon/system that includes at least 1 tag from the filter.  The new filter will now only include every weapon/system that possesses ALL tags from the filter.
Closes #1849
=> feat(compendium):change tag search to 'AND' logic

src/features/main_menu/_components/startup_logs/horus.ts
This PR fixes the `n(...).split is not a function` error in `horus.ts` by setting the `require` statements to return their "default", similar to what we see in `io/Generators.ts`.  At time of writing, this does *NOT* fix the initial load of the theme always defaulting to GMS; that part is a WIP.
UPDATE: I'm almost certain that the GMS default start has been present since before the performance update.  After doing some tests, the GMS startup runs because the UserProfile's theme is undefined, probably because the deserialization hasn't completed by the time the GMS switch case begins.  We may ultimately want the typer to wait until the UserProfile is properly deserialized, but I'd say that's an issue for another day.
Closes #1829
=> fix(homepage): fix .txt 'require's in horus.ts

src/features/nav/pages/ExtraContent/PackInfo.vue
This fix includes "backgrounds" under the `humanReadableMap` when summarizing Pack Info from an LCP.
Closes #1857
=> fix(Packs):include backgrounds in pack summary

src/features/nav/pages/Help.vue
This change shortens the FAQ on the COMP/CON app and includes a link to the [COMP/CON Wiki FAQ](https://github.com/massif-press/compcon/wiki/Frequently-Asked-Questions).
Closes #1889
=> feat(help): shorten app FAQ, point to wiki FAQ

src/classes/components/group/GroupController.ts, src/features/pilot_management/PilotSheet/components/CloneDialog.vue, src/features/pilot_management/Roster/index.vue, src/features/pilot_management/store/index.ts
Start of revisiting Pilot Groups in the context of the cloud rework.  Goal was to convert `pilot_groups_v2.json` into a data structure purely for ordering and configuring groups, with no knowledge of each group's pilots.  
Sorting within groups is handled via SortIndex.  The intent is for SortIndex to be preserved when adding a pilot if that pilot has a defined SortIndex of 0 or higher, so that when a user logs into CompCon, all of their pilots preserve their sorting.  Moving a pilot refreshes all sort indices (unsure if good practice; feedback appreciated).
Current challenge is acquiring the desired sort index when moving from one group to another.  Some of the means I've been using to maintain the sort order may be interfering with how cross-group sorting works.
As an aside about this: …
=> fix(Roster): revisit pilot groups

src/classes/components/counters/CounterController.ts, src/classes/npc/Npc.ts
This PR adds a CounterController to the NPC class to avoid errors getting thrown when retrieving CounterData within the Mission Runner.  It also makes the FeatureController counter check optional depending on whether there's actually Features within the FeatureController.
=> fix(npc): give NPCs CounterControllers, optl FeatController counts

src/features/encounters/encounter/components/EncounterCard.vue
This change looks at the currently selected encounter to update the default value for the sitrep select.
Closes #1843
Closes #1886
=> fix(encounter): Correctly display the sitrep of selected encounters

src/classes/pilot/Pilot.ts
This change will skip deserializing the group of a pilot upon a cloud sync operation, but allows for deserialization, which is important for loading backups.
Unknown, but mentioned as a pain point in Discord
=> fix(Sync): Prevent pilot groups from being sync'd

package.json
It is apparent that I haven't done any work on this in a while. I am sorry, but while I realized that the new `vue-cli-service serve` does allow for access off of locahost, it does not use https by default which is a requirement.
This works for me, accessing the dev server off of the dev machine, but I cannot test localhost access.
Will one of you please check on your end and see if this change causes an issue for that (more common ) usecase?
=> feat(dev): Make the dev server https capable

src/classes/mech/Mech.ts
This PR updates the Mech class to register the parent pilot's ReservesController so any relevant bonuses are applied (e.g. Extra Repairs adding 2 to repcap).
Closes #1938
=> fix(mech): register mech's Pilot's reservescontroller

src/classes/CompendiumItem.ts, src/classes/pilot/components/Loadout/equipment/PilotEquipment.ts, src/ui/components/panels/loadout/pilot_loadout/_PLCardBase.vue, src/ui/components/panels/loadout/pilot_loadout/_PLGearCard.vue
This PR allows for instantaneous updating of the Description and DamageTypeOverride of pilot gear by initializing the `_flavor_description` and `_custom_damage_type` properties, respectively.  Learned from the fix to #1923 which had a similar fix.
Closes #1840
=> fix(pilot): initialize pilot gear damage & desc

CONTRIBUTORS.md, package.json
This adds an additional build command to allow for https enabled developer servers without modifying the existing dev command.
=> fix(dev): Create new run command to enable an https developer server

src/features/nav/pages/ExtraContent/PackInfo.vue
Small bugfix for a non-breaking issue.  Adds Bonds to the PackInfo's humanReadableMap.
=> fix(content): Added Bonds to readable map

src/features/ui_test/index.vue, src/ui/components/CCDiceMenu.vue
Currently, adjusting accuracy or difficulty on an "autoroll" re-rolls every dice. This can cause frustration when a hit ( or especially a critical hit ) becomes a miss after adding accuracy, due to a drastically different base die roll, usually d20.
This change only re-rolls the accuracy / difficulty di(c)e when changing the preset accuracy. Please not that this does re-roll EVERY d6. This means that clicking the + button from 1 accuracy to 2 accuracy the total could go down, but never below the base value. The converse is true of difficulty, we will not longer have a miss turn into a hit after adding difficulty.
Closes #1819 
=> fix(Active Mode): Make accuracy/difficulty adjustment more sane

src/features/main_menu/_components/CCLog.vue, src/features/main_menu/_components/startup_logs/gms.ts, src/features/main_menu/_components/startup_logs/horus.ts, src/features/main_menu/_components/startup_logs/msmc.ts
Perform some minor adjustments to the CCLog spacing so that it doesn't immediately start cut off at the top and occupies more of the webpage.
None currently
=> fix(style):adjust CCLog spacing to display more content

src/classes/pilot/Pilot.ts
Serializing pilot Special Equipment will treat Pilot Armor and Pilot Weapons as "PilotGear" since the CompendiumStore treats all Pilot-equipped items as "PilotGear" with a subcategory of "gear", "armor", or "weapon".
Closes #1776
=> fix(pilot): Pilot Armor/Weapons serialized as gear in SE

src/classes/utility/ItemFilter.ts, src/ui/components/cards/_MechWeaponCard.vue
This PR Changes the filters for Frames such that all Role and Mount selections must match for a Frame to be displayed. For example, Caliban will appear for when the Roles "Controller", "Striker", and "Controller+Striker"  are selected, but not "Controller + Defender".  In a similar way, Caliban will appear when "Heavy" mount is selected, but not when "Heavy + Flex" mounts are selected.  This is a similar change to #1860.
Closes #1966
=> feat(Compendium): use AND filter on Frame role/mounts

src/ui/components/panels/loadout/active_loadout/dialogs/downtime/_GetOrganized.vue
This change fixes the Get Organized downtime action in Active Mode to match the rules. Specifically, this addresses improvement roll results of 9 or less, when the player needs to reduce BOTH Efficiency and Influence by 2 (to a minimum of 0) OR take action. Below is the relevant ruling from the core book, pg. 55:
#1847
=> Issue #1847 - fix GetOrganized active mode

src/features/pilot_management/PilotSheet/sections/mech/components/MechNav.vue
Changed pilot button in mech nav to go to tactical profile, as that's where you go to change talents and licenses which is a far more common action than wanting to go back to the pilot narrative page. Also commented out redundant link back to itself and to unfinished combat analytics. They can be restored if/when the feature is ready.
Question: Should I leave them commented to save future work, or should that be left to the version control and it be deleted for tidiness?
=> refactor(mech nav): pilot button to tactical profile, removed options

src/features/pilot_management/PilotSheet/components/PilotEditMenu.vue, src/features/pilot_management/PilotSheet/components/PilotNav.vue, src/features/pilot_management/PilotSheet/components/ShareDialog.vue
This PR prevents users from creating Share Codes for remote pilots from the Pilot Roster, instead matching functionality with the Pilot Management Navbar.  It also improves error handling when an error occurs while generating/refreshing a share code.
Closes #1970
=> fix(pilot): roster remote refresh, error handling

src/features/compendium/components/views/components/_cCardBase.vue, src/ui/components/selectors/views/_SelectorCardsView.vue, src/ui/components/selectors/views/components/_cCardBase.vue
This PR includes a `&nbsp;` after a CompendiumItem's Source (if present) to provide better readability on Compendium/Selector Cards view.  Also renames the SelectorCardsView's component for easier dev navigation using Vue webtools.
Closes #1986
=> fix(ui): cardview space b/t name & type

src/classes/pilot/components/license/License.ts, src/features/compendium/store/index.ts
This PR additionally filters licensed items and Variant Frames by "source" (aka Manufacturer abbreviation, like HA or IPS-N).  This is a stopgap fix for homebrew LCPs with matching Frame Names.  In the future, we will probably want to implement a "parent ID" data field for Weapons, Systems, Mods, and variant frames.
Partially covers #1981, but additional work would be good to make this more robust.
=> fix(compendium): create Licenses using 'source' filter

src/features/pilot_management/PilotSheet/sections/mech/components/MechNav.vue, src/features/pilot_management/routes.ts
Added missing  tactical profile route to routes.ts, to make pilot page link to tactical profile work (my bad)
`#1978`
=> fix(mech nav): fix broken pilot page link

src/classes/Statblock.ts, src/features/pilot_management/PilotSheet/components/StatblockDialog.vue, src/features/pilot_management/PilotSheet/sections/mech/components/MechNav.vue, src/features/pilot_management/PilotSheet/sections/mech/index.vue
Submitting as draft as I am once again stuck.
Changes made to remove friction from build sharing:
- Changed stat export type selection to radio buttons to simplify process.
- Made compact mech stats default option.
- default mech is active mech > last created mech > blank in that order.
- Rearranged full mech+pilot stat block to group concerns better.
- Added caveat that emoji don't work with Discord code block formatting.
Also added Bonds to pilot stat share.
###HELP: 
Sticking point is getting s default mech set and read by the `get statblock()` function without either breaking the mech selection dropdown or having a bunch of errors thrown for pilots with no mechs, e.g. fresh  ones.
Finally getting the default mech to work broke the mech selection dropdown - it now only gives stats for …
=> 1887 [FEATURE]Generate Statblock Revision

src/features/nav/pages/ExtraContent/PackInfo.vue
Hopefully the final one for a while: Adding humanized text fields for LCP Installation for Reserves and Factions that could be included in an LCP (factions seem to have been deprecated but I'm including them in case they make a comeback).
=> fix(lcp): humanize reserves and factions in LCP import

src/features/nav/index.vue, src/features/nav/pages/Help.vue, src/features/pilot_management/PilotSheet/components/PilotNav.vue, src/features/pilot_management/PilotSheet/sections/mech/components/MechNav.vue
This PR adds a clear "Help & FAQ" button to the top navbar when away from the main page. It adds direct links to the COMP/CON FAQ to the top of the Help page. In addition, small styling tweaks have been made to the pilot/mech navbar.
=> feat(help): add help icon, FAQ links, some style

src/features/encounters/mission/runner/components/PlayerCard.vue, src/features/pilot_management/ActiveSheet/layout/MedPipLayout.vue, src/features/pilot_management/ActiveSheet/layout/PipLayout.vue
This PR removes some hardcoded "magic numbers" from the Active Mode overcharge logic. It relies upon the mech's OverchargeTrack property to determine maximum pips for the Overcharge selection. It removes hardcoded Overcharge logic from MedPipLayout.
Inspired by #2030, though it doesn't directly close the issue.
=> fix(Active Mode): dynamically determine overcharge pips

src/features/nav/pages/Help.vue, src/features/pilot_management/PilotSheet/components/ExportDialog.vue
This PR removes references to Roll20 in the UI. The mention of Roll20 often leads users to ask how to import their pilots to Roll20, so this change is to clarify the state of the world between COMP/CON and Roll20.
None yet.
=> fix(ui): remove ui references to Roll20

src/classes/components/feature/deployable/Deployable.ts
According to rules helpers on Pilot NET, deployables that can be "redeployed" can be redeployed without being recalled (i.e., "redeploy" combines the "recall" + "deploy" actions into a single action). This PR adds a "Redeploy" action to deployables with "redeploy" set, for action tracking purposes. It retains the original "Redeploy" functionality since it facilitates stat tracking for the deployables once they are recalled.
Known issues: The "Redeploy" action doesn't appear in the Compendium, but does appear in Active Mode. Also, Jericho Portable Cover will have the "Redeploy" button, though it is inappropriate. If anyone has feedback on how to make this work more effectively, please leave a comment!
~~Also, if it turns out that the interpretation of the rules above is incorrect, please …
=> feat(deployable): add redeploy action to redeployables

src/features/compendium/store/index.ts
Changed the way that the Actions are retrieved from the store. The built in filtering in the "@Brewable" method decorator didn't seem to working, and my guess is it's because Action does not inherit the CompendiumItem class. I switched the get method to use the same pattern as Backgrounds, which also don't inherit CompendiumItem.
There are a couple of other classes being retrieved by "@Brewable" that also don't inherit from CompendiumItem: Tags, Manufacturers, and Reserves. I will be testing those next, but I need to whip up a custom LCP that adds some custom items of that type in (unless there's one available that someone knows about already).
After that I do plan on looking into adding LCP source tags.
Closes #2025
Closes #2076
=> fix(lcp filtering): filter Actions based on lcp active status

src/classes/components/mechskills/MechSkillsController.ts
This PR changes the Parent type for MechSkillController to be `Pilot` like the other controllers. It also allows LL0 characters to benefit from `mech_skill_point` bonuses, as there was a previous check for the `Level` property that short-circuited the MaxHASEPoints bonus calculation.
It is unclear why the parent type was previously `IHASEContainer`; if clarification could be provided as to why the Parent type should *stay* `IHASEContainer`, we can come up with an alternative solution that checks for a `null` or `undefined` value of `Level` instead of simply a false-y one (since `0` would be treated the same as `null` or `undefined` in the context of 2.3.9a's MaxHASEPoints method).
Closes #2070
=> fix(pilot): use Pilot as MechSkillController.Parent

src/classes/mech/components/equipment/MechEquipment.ts, src/classes/pilot/components/Loadout/equipment/PilotEquipment.ts
This PR fixes a typo in MechEquipment and PilotEquipment checking for `tg_indestructable` instead of `tg_indestructible`.
Closes #2066
=> fix(Active Mode):fixed indestructible tag typo

src/classes/mech/components/loadout/MechLoadoutController.ts, src/ui/components/panels/loadout/mech_loadout/components/system/_SystemsBlock.vue
This PR introduces a `watch` on the `activeSystems` computed property from a given Mech Loadout, and updates the SystemsBlock data appropriately (this is pulled from the pattern on the pilot roster `Roster/index.vue` when the `plength` would change). It also adds a Vue.set update on loadouts changes for safety, and cleans up how loadouts are assigned when added or copied.
Closes #2138
=> fix(mech): update loadout systems on loadout change

src/classes/Statblock.ts, src/features/pilot_management/PilotSheet/components/PilotRegistrationCard.vue, src/ui/components/selectors/CCCoreBonusSelector.vue, src/ui/components/selectors/CCTalentSelector.vue
This PR adds `.toUpperCase()` transformations to Talent and Core Bonus names in select places. It also capitalizes the names of mounts in printed, plaintext statblocks. This is part of a drive to make statblocks more readable, and make Lancer-Data easier to stylize for 3rd-party creators.
=> feat(UI): modify caps handling for mounts, CBs, Talents

src/features/encounters/npc/index.vue
The vuetify data table component already gives us searching by every column defined in the headers array. I just needed to point the Class column to the actual name property of the NpcClass object. So this is sort of a bug fix, but hey, I'm up for calling it an expanded feature.
Closes #2102
=> FIX: enable npc search by class

src/features/main_menu/_components/login/SignIn.vue
Replaces the regex email validation with just the bare minimum of checking for a valid email address. That's all I wanted, and thought the regex would be a bit more full featured. Didn't realize how inefficient it was.
Closes #2119
Closes #2128
=> FIX: email validation regex is inefficient

src/ui/components/panels/loadout/active_loadout/CCCombatDialog.vue, src/ui/components/panels/loadout/active_loadout/components/_ItemSelectorRow.vue, src/ui/components/panels/loadout/active_loadout/dialogs/action/_FullTechDialog.vue
**Fix for #2088** 
The problem here was that the "used" property (which is what is supposed to trigger the roll component to show up) was not being updated on the Hurl Into the Duat ability, or any ability that was used through the Full Tech dialog due to "used" being tied to the action.Used property, which is only updated on commit. That doesn't happen in the Full Tech dialog until that dialog's confirm button is pressed.
So I changed it to only ever look at the Tech Attack property. I can't find a reason why we should be using something else, since that ternary in CCCombatDialog.vue was explicitly controlling the tech-attack component visibility. I did as much testing as I could, but maybe I missed a case where the action.Used should be checked instead?
Finally, I made changes to the …
=> FIX: Full tech fixes

src/features/nav/pages/Help.vue
Quick fix to redirect the Troubleshooting link in the Help menu to the new wiki page.
Closes #2110
=> fix(help): redirect Troubleshooting to new wiki page

src/features/main_menu/_components/login/SignIn.vue, src/features/main_menu/_components/login/SignUp.vue
This PR fixes a bug introduced in #2038, where the default behavior for an HTML form is to refresh the page upon a submit. This prevents the usual submit action on login/signup and thus prevents the refresh, while still letting a user sign in as usual and preserving the "press Enter to submit" functionality of the HTML forms.
Closes #2122
=> fix(login): prevent refresh on v-form submit

src/ui/components/panels/loadout/mech_loadout/components/system/_SystemsBlock.vue
Adds a drag and drop toggle for the reorderable systems for mobile (same feature that's on the pilots component).
I'm not in love with the positioning here since it creates a lot of whitespace, but adding it up on the systems legend alongside the system point count was getting too crowded on mobile screens. At least it's consistent with the pilot control?
Closes #2095 
=> FIX: add toggle for system reorder

src/features/compendium/Views/NpcClasses.vue
Originally, only names and roles could be sorted in the NPC class list within the compendium. Now, classes can be sorted by their other stats as well. I had to make a special exception for the evasion stat because it is referenced as both "evasion" and "evade" through out the code base. Another exception had to be made for the structure and stress stats as they are the same across all classes and tiers, therefore they are not factored into the sorting process.
Closes #840
=> Implemented NPC Class table sorting

src/classes/mech/ActiveState.ts
When in Active Mode, changing your mech's HP or Heat will now properly record the *difference* by which it changed. Additionally, the mission stats will only change when when taking damage/heat, not when they are restored/cleared.
Structure Lost and Reactor Stress are also now recorded when HP is lost and the Heat Cap is exceeded. To make things easier to read, messages reporting current Structure and Reactor percentages now display values as percents rather than decimals.
Closes #1994 & #1995
=> Fixed combat log tracking hp/heat properly

src/features/compendium/store/index.ts, src/ui/components/panels/filters/_FrameFilter.vue, src/ui/components/panels/filters/_MechSystemFilter.vue, src/ui/components/panels/filters/_MechWeaponFilter.vue, src/ui/components/panels/filters/_WeaponModFilter.vue
The compendium filters for content packs defaulted to grabbing pack names from available Frames in the compendium, instead of directly from the compendium's ContentPacks. This means that an LCP that has *no frames* will lack a content pack filter in the Compendium (e.g. for an LCP that only has non-frame Exotic Gear). This PR adds a method to retrieve LCP Names based upon ContentPacks in the compendium.
However, since Lancer Core Data isn't treated as a Content Pack, we still need an alternative way of adding the Lancer Core Data as an option for the filters. We could hardcode the packname, but I felt more comfortable performing a union of the pack names derived from Frames and ContentPacks. Perhaps one day in the future, the Lancer Core Data will be considered its own Content Pack, …
=> fix(compendium): collect packnames directly + Lancer Core

src/classes/components/feature/synergy/Synergy.ts
Synergy.Collect will now always use lodash's `uniq` method, even if no item is provided.
Closes #1968
=> Ensure Synergy.Collect returns unique elements

src/classes/components/save/SaveController.ts
Think I've fixed the cloud sync problem along with @ptlm500.
Initially we diagnosed the problem with cloud syncing but also noticed a problem also occurred with local changes not persisting across browser refreshes. For example changing a pilot's name on refresh (with auto-sync off) forced the name to return to it's previous version.
It is related to the `save()` function in `src\classes\components\save\SaveController.ts`
Removing the `|| !this._isLoaded` from the if statement on line 33 makes the cloud save seem to be functional as well as local changes.
The save function was being bypassed by this early return after the vast majority of changes we tested in the UI.
Certain changes did persist on changes to the pilot profile such as level ups.
```
public save(skip?: boolean) {
if (skip) …
```
=> Remove isLoaded flag from save function to improve browser and cloud saving.

package.json, src/cloud/lcp_sync.ts, src/features/nav/pages/ExtraContent/components/DirectoryTable.vue, yarn.lock
This PR uses the `semver` library to coerce and compare LCP versions to determine the latest LCP version. This is used both in the LCP Directory tab of the Content Manager and in the LCP Sync menu under Cloud Account Management. 
This was made in response to the current method of version comparison being simply removing the `.`s from a version and comparing the resulting string. This resulted in The Long Rim v1.2.0 appearing less recent than v1.0.11, since the versions would shorten to 120 and 1011, respectively, and thus the older 1.0.11 would appear "greater" in comparison. Ergo, when "Sync All" would be performed, Long Rim 1.0.11 would overwrite 1.2.0, which is undesirable behavior.
As a note: I was unable to properly test this in the Sync menu since backend updates have restricted …
=> use semver to compare versions

src/classes/Statblock.ts, src/features/encounters/mission/runner/components/EncounterNav.vue, src/features/encounters/npc/index.vue
Added an option while running a combat encounter to generate a text stat block for the currently selected NPC.  Also added additional info to the current NPC stat block generation to include current HP, Heat, Structure, and Stress.  The dialog that shows the NPC statblock in both the NPC Roster page and the Encounter page both have a "Copy to Clipboard" option too.
Tried adding feature effect text to the stat block, but found it was far too much with how simplified the plaintext stat generation is.  I'd suggest screenshots to share full effect information for NPC features when applicable.  I could see a separate dialog for full NPC feature information if that's desired by someone in the future.
Generate NPC Statblock option
Statblock example from Encounter:
Statblock example from NPC …
=> feat: allow generating npc stat block in encounter

src/classes/pilot/components/Loadout/PilotLoadout.ts, src/ui/components/panels/loadout/pilot_loadout/CCPilotLoadout.vue
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
the gear slots granted by the extended harness were hardcoded so any similar homebrew additions wouldn't be functional, this adds that feature. 
`#1747`
small changes to the main codebase, allowing non-extended harness options to be used while keeping most of the functionality as before. there will need to be a change to the documentation and usage of the base lancer-data, which I have already fixed and made a pull request on that git page.
=> added feature #1747 unhardcoded gear slots

src/classes/components/feature/FeatureCollector.ts
Fixing an issue where using an action from a pilot talent during an encounter would make it disappear from the list of actions for the rest of a combat encounter instead of just becoming unusable until it is able to be used again based on frequency.
N/A
- [x ] Bug fix (non-breaking change which fixes an issue)
=> fix: correct typo in feature collection comparison

src/classes/mech/components/loadout/MechLoadout.ts
Updated the Mounts getter for MechLoadout to include integrated weapons.
Adding example before and after images for Barrage action from the Actions footer, but similar results are shown for Skirmish and Overwatch from this change.
Before change(the mech has a GMS Pistol as an Integrated Weapon):
After change:
#2254
=> fix: add integrated weapons to Mounts getter for MechLoadout

src/classes/Statblock.ts
This fixes an issue where generating a "Mech Build" or "Full" stat block would only output one Integrated Mount if there are multiple.
Example of Mech Build output after changes:
Example of Full output after changes:
I think there could be a future issue to clean up the stat block generation logic.  There is code that generates the same info two different ways between "Mech Build" and "Full" stat block generation, but didn't want to refactor as part of this, just wanted to fix the specific issue for now.
#2161
=> fix: updating mech stat block generation to output all integrated mounts

src/ui/components/panels/loadout/active_loadout/components/_ItemSelectorRow.vue, src/ui/components/panels/loadout/active_loadout/components/_WeaponAttack.vue, src/ui/components/panels/loadout/active_loadout/dialogs/action/_OverwatchDialog.vue, src/ui/components/panels/loadout/active_loadout/dialogs/action/_ReturnFireDialog.vue, src/ui/components/panels/loadout/active_loadout/dialogs/action/_SelBarrageDialog.vue, src/ui/components/panels/loadout/active_loadout/dialogs/action/_SelSkirmishDialog.vue
Added automation of the Return Fire reaction.
Usage:
- Click "Return Fire" reaction
- ![image](https://github.com/massif-press/compcon/assets/9093363/4ec0be2a-045d-4bc2-acb0-2f66b57a31df)
- Weapon selection dialog will show.  It will only show Auxiliary Ranged weapons.
- ![image](https://github.com/massif-press/compcon/assets/9093363/77d6d003-79a9-46da-8a31-75b693dfad82)
- After selecting the weapon, the Weapon Attack dialog will show, allowing to automatically roll attack and damage
- ![image](https://github.com/massif-press/compcon/assets/9093363/3df193f3-2f82-4494-bc51-2206b5ef3149)
- In this example, since we are using Hand Cannons, we can see the attack even unloaded the weapon used, as expected
- ![image](https://github.com/massif-press/compcon/assets/9093363/371065ff-7983-4f9f-b33f- …
=> feat: return fire automation

src/features/pilot_management/Print/MechPrint.vue
This [issue](https://github.com/massif-press/compcon/issues/2267) highlighted that certain systems were missing from the Mech Print out, namely systems like Walking Armory. Taking a look, I found that [it](https://github.com/massif-press/compcon/blob/012b7ee3b8e1460218aa8d29e07aa23177dabd7f/src/features/pilot_management/Print/MechPrint.vue#L299) was using `mech.MechLoadoutController.ActiveLoadout.Systems` which does not include `IntegratedSystems`, so I updated it to use `AllActiveSystems` instead.
`#2267`
- [ x ] Bug fix (non-breaking change which fixes an issue)
=> fix 2267: Integrated Systems now show in Print

src/classes/Interfaces.d.ts, src/classes/mech/Mech.ts, src/classes/mech/components/loadout/MechLoadout.ts, src/classes/mech/components/loadout/MechLoadoutController.ts, src/classes/mech/components/mount/EquippableMount.ts, src/classes/mech/components/mount/Mount.ts, src/classes/pilot/Pilot.ts, src/classes/pilot/components/corebonus/CoreBonusController.ts, src/classes/pilot/components/reserves/ReservesController.ts, src/classes/pilot/components/talent/PilotTalent.ts, src/classes/pilot/components/talent/TalentsController.ts, src/ui/components/panels/loadout/mech_loadout/CCMechLoadout.vue, src/ui/components/panels/loadout/mech_loadout/components/mount/_MountBlock.vue, src/ui/components/panels/loadout/mech_loadout/components/mount/weapon/_WeaponSlotCard.vue
added some functionality for generalized mount bonuses (issue #1992 )
`#1992
The new functionality allows any Reserve, Talent, or Core Bonus to add the following bonus details and it should add an appropriate mount to all available mechs on the pilot that received them:
"bonuses": [
{
"id": "mount_modification",
"val": [
"A",
"B",
"C",
"D",
"E"
]
}
where:
A- a MountType enum, the kind of mount that will be added (I.E whether it is a main mount, aux/aux, heavy, etc.) this much match the capitalization  and style of a mount type enum.
B- whether or not this is an integrated mount (true or false should be the only inputs, no capital letters)
C- whether or not this mount should be modifiable (true or false)
D- the number of mounts to check against …
=> allowed extended weapon mount functionality

src/classes/Statblock.ts, src/classes/npc/NpcFeature.ts, src/classes/npc/NpcItem.ts, src/classes/npc/NpcReaction.ts, src/classes/npc/NpcSystem.ts, src/classes/npc/NpcTech.ts, src/classes/npc/NpcTrait.ts, src/classes/npc/NpcWeapon.ts, src/features/encounters/npc/index.vue
This adds two options when generating NPC statblock: ``compact`` and ``detailed``.
Compact mode is the exact same as the existing functionality, and is the default option.
Detailed mode is the new feature, providing description of each feature.
This feature can be accessed by
1. Go to Encounter Toolkit>NPC Roster
2. Click the gear icon next to NPC name. Select Generate NPC Statblock.
3. Right above the textbox, there are two radio buttons labeled Compact and Detailed. Select desired option.
- Provide Scan results quickly
- Save time spent on checking rulebook
- Stepping stone for [Issue 535: Print Improvements](https://github.com/massif-press/compcon/issues/535#issue-557051707)
@ApprenticeofEnder for providing guidance on implementing polymorphic method for subclasses of ``NPCFeature``.
=> feat: add detailed NPC statblock option

src/features/nav/pages/Help.vue
This change simply corrects a small typo on the help page regarding LCP downloadable files.
`N/A`
=> fix typo in help page

src/features/main_menu/_components/login/SignUp.vue
This PR updates the RegEx pattern used for emails to include support for subaddressing. This was added with [RFC5233](https://datatracker.ietf.org/doc/html/rfc5233).
=> Add support for email subaddresses (plus aliases)

src/classes/pilot/components/Loadout/equipment/PilotEquipment.ts, src/classes/pilot/components/Loadout/equipment/PilotWeapon.ts
moved the effect data higher up from weapon level to pilot equipment level bc the effect field is used/needed in all: armor, gear and weapons
now all those pilot equipments can render an effect field if the data provides it (should therefore be backwards compatible)
`[
{
"id": "effected_gear",
"name": "Test Reserve",
"type": "Gear",
"effect": "nananana",
...
}
]`
gear
weapon
armor
`#2347`
As a note to reviewer: we could also put the effect field in gear, weapon and armor seperatly in favor of readability but thats more of an architectural decision.
=> fix #2347 optional effect-field to pilot equipment

src/classes/npc/NpcTech.ts, src/classes/npc/NpcWeapon.ts, src/features/encounters/npc/index.vue, src/features/encounters/npc/print/NpcPrint.vue, src/features/encounters/routes.ts
- Can print NPC sheets by going to ``/printNpc/{npcId}`` NPC sheet print button no longer disabled.
- Refactored a portion of generateSummary() in NpcWeapon.ts and NpcTech.ts into its own function, AttackSummary(). This function is used in NpcPrint.vue for displaying hit bonus and accuracy for each weapon.
- Mostly used the same styles used in PC printable sheets.
- Reorganized a bit to fill up empty spaces (NPCs don't have core powers, repairs, etc.)
[`#535`](https://github.com/massif-press/compcon/issues/535) Print Improvements
=> feat: Print NPC Sheet

src/features/encounters/mission/runner/Active.vue
The Vue container in Active.vue was trying to use the MissionStore before it fully loaded, resulting in it being undefined.  This adds a condition on the container to see if there is an active mission that is truthy and displays the content if it is.
If there are active missions in the store, but there are none found (e.g. the UUID for the active mission is invalid in the route path), then it will display an error message.
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
unknown if any
=> Fix mission runner page refresh race condition.

src/classes/Background.ts, src/features/pilot_management/New/pages/SkillsPage.vue, src/ui/components/selectors/CCBackgroundSelector.vue
Suggest Skills button now imports example triggers from background. Button was previously marked as ``Feature In Development``.
[#2343](https://github.com/massif-press/compcon/issues/2343)
=> Suggest Skills button imports example triggers from background

src/features/nav/index.vue
Adds names found in tooltip to `aria-label` on icon button to make them accessible to screen readers (previously read just "button").
For the compendium button, unwraps the anchor around it to prevent multiple nested focusable elements, which can confuse unsighted users.
For the vertical dots menu button, adds the `attrs` from the `v-menu`, which adds aria attributes like `aria-expanded` to help unsighted users understand that the button causes something to open and close.
N/A
Bug fix (non-breaking change which fixes an issue)
=> [A11Y] Add accessible names to icons in nav menu

src/features/encounters/components/GMLog.vue, src/features/main_menu/_components/CCLog.vue
Adds null alt text to the left and right images in the GM log to prevent screen readers from reading the source file name. This can be a bewildering experience for unsighted gamers. It's a violation of WCAG 1.1.1 and Section 508 1194.22.
For a detailed summary of the issue and solution, see [this page from Deque University on the subject of alt text requirements](https://dequeuniversity.com/rules/axe/4.9/image-alt).
`#N/A`
This is low-hanging accessibility fruit-- I'll make some issues for more challenging problems.
Bug fix (non-breaking change which fixes an issue)
=> [A11Y] Prevent screen readers from reading decorative images in GM Log

src/classes/Action.ts, src/ui/components/cards/_EquipmentCardBase.vue, src/ui/components/items/features/actions/CCAction.vue, src/ui/components/items/features/actions/_actionBase.vue, src/ui/components/items/features/actions/_actionPanel.vue, src/ui/components/items/features/actions/_actionPopup.vue
Flavor text field added to actions. Previously, items could have flavor texts, but actions could not.
The visibility of flavor text is optional, and can be controlled by `displayDescription` prop in `_actionBase.vue` and components that call `_actionBase.vue` directly or indirectly.
[`#2444`](https://github.com/massif-press/compcon/issues/2444)
=> Feat: Description Field to Actions

src/ui/style/typography.css
It's being set to #EEE for no good reason. That's not correct. This just removes that so it inherits the correct text color from the theme's settings.
Yay for single line PRs.
=> Don't override ra-quiet color to white on all themes

src/classes/mech/components/loadout/MechLoadout.ts, src/ui/components/panels/loadout/mech_loadout/components/mount/weapon/_ModSelector.vue, src/ui/components/panels/loadout/mech_loadout/components/mount/weapon/_WeaponSelector.vue, src/ui/components/panels/loadout/mech_loadout/components/system/_SystemSelector.vue
Previously, only special equipment stored under the pilot was being aggregated and displayed in equipment selectors, so only talents/core bonuses allowed you to add special equipment. Now, a given active mech loadout will be considered (active so you must actually have the source item equipped) and its special_equipment content added to your menus.
=> Correctly analyze mounted systems/weapons/mods for special equipment

src/ui/components/CompendiumBrowser/CCCompendiumBrowser.vue
fixed an issue in the compendium where selecting an item caused it to not scroll at the correct location 1 time out of 2
tested on firefox, chrome and edge
=> compendium select scroll issue fix

src/classes/mech/components/loadout/MechLoadout.ts
It turns out that since CBS are applied to both Pilots & Mechs, the code collecting IWs/ISs can and will accidentally duplicate them. In lieu of refactoring the collectors to take a context or something, I've made the executive decision to just... not support adding the same thing as an integrated weapon bonus twice. This should have zero negative effects, since integrated gear is generally supposed to be entirely unique (and therefore there's no other second thing to apply it). I'm tentatively open to revisiting this if there's a genuine need for it that can't be solved with "This weapon can be attacked with twice in a Barrage" or something similar, though.
I've tested this decently thoroughly, but I'd appreciate a sanity test before this is merged by anybody else - I checked by using a …
=> Fix dupe integrated weapons when granted by CBs
