- TODO
- src/renderer/store/modules/configs.js
- src/renderer/store/modules/datastore.js
- src/renderer/store/modules/pilots.js
Fixes a bad action dispatch that prevents users from deleting configurations
> fix broken delete config

- TODO
- src/renderer/components/Roster/ConfigSheet/LoadoutEditor/MountBlock.vue
- src/renderer/components/Roster/UI/Sidebar/SidebarItem.vue
- src/renderer/components/Roster/UI/Sidebar/index.vue
- src/renderer/components/Roster/index.vue
- src/renderer/store/modules/configs.js
- src/renderer/store/modules/pilots.js
- static/generators/callsigns.txt
Fixes https://github.com/jarena3/compcon/issues/9
> fix cloned pilot configs referencing original pilot

- src/renderer/components/Roster/ConfigSheet/Print/PrintView.vue
- src/renderer/components/Roster/ConfigSheet/index.vue
Fixes https://github.com/jarena3/compcon/issues/18
> fixes improved armament mounts showing up incorrectly

- src/renderer/components/Roster/PilotSheet/Level/index.vue
fixes https://github.com/jarena3/compcon/issues/20
> fixes missing new license in level up core bonus selector

- package-lock.json
- src/renderer/components/Roster/UI/Sidebar/index.vue
- static/data/translationTable.json
merge gsheet importer & new dialogs
> add dialogs etc. for gsheet importer

- TODO
- src/renderer/components/Roster/ConfigSheet/LoadoutEditor/ModTable.vue
- src/renderer/components/Roster/ConfigSheet/LoadoutEditor/SystemTable.vue
- src/renderer/components/Roster/ConfigSheet/LoadoutEditor/WeaponTable.vue
- src/renderer/components/Roster/PilotSheet/LoadoutEditor/ItemTable.vue
- src/renderer/components/Roster/UI/Sidebar/SidebarItem.vue
> improve visibility of new config and remove item buttons

- TODO
- src/renderer/components/Roster/PilotSheet/Selectors/BackgroundSelector.vue
- src/renderer/components/Roster/PilotSheet/index.vue
merge custom background pilot feature
> add custom background option to background selector

- TODO
- src/renderer/components/Roster/ConfigSheet/Print/PrintView.vue
- src/renderer/components/Roster/UI/Tag.vue
- static/data/tags.json
- static/data/weapons.json
fixes:
- config sheet not printing
- rolled limited bonuses (eng. prototype weapon) not taking limited systems bonus
- CORE integrated weapons not printing
- Talent weapons/systems not printing
- config armor not printing
> various print fixes

- src/renderer/components/Roster/ConfigSheet/LoadoutEditor/MountBlock.vue
- src/renderer/components/Roster/ConfigSheet/index.vue
- src/renderer/components/Roster/PilotSheet/LoadoutEditor/PilotLoadout.vue
- src/renderer/components/Roster/PilotSheet/index.vue
- src/renderer/components/Roster/RosterView/PilotCard.vue
- src/renderer/data_interfaces/mech.d.ts
- src/renderer/logic/stats.ts
adds raw text statblock output to pilot and config sheets
(also fixes sal core bonus effects not updating instantly)
> Statblock raw

- package.json
- src/main/index.unit.test.js
- src/tests/int/example.int.test.js
- yarn.lock
- Add Jest testing framework
- Add sample tests with proposed organizing
convention for tests
> Add Jest testing framework

- src/renderer/features/gm_toolkit/components/EncounterRunner/RunnerNpcCard.vue
- src/renderer/features/gm_toolkit/logic/Tips.ts
- src/renderer/features/gm_toolkit/logic/templates.ts
- src/renderer/features/gm_toolkit/static/systems.json
- src/renderer/features/gm_toolkit/static/template_systems.json
- Fixes Commander suggested trait counter counting its own default trait (#304) 
- Various data fixes reported in lancer-data (close massif-press/lancer-data#45, close massif-press/lancer-data#43, close massif-press/lancer-data#42, close massif-press/lancer-data#41)
> mostly NPC data fixes

- src/main/index.js
- src/renderer/features/_shared/classes/WeaponMod.ts
- src/renderer/features/pilot_management/ConfigSheet/LoadoutEditor/MechWeaponItem.vue
- src/renderer/main.ts
Fixes #285. Also fixes Vue dev tools in most situations.
For 285:
- Button now deactivates if no legal mod for that mount
- Button is larger and has text, 'Mod'
- Button color is blue when active
> Tso bug 285

- .travis.yml
Fixes weird CI error that folks submitting pull requests are getting.
> Tso ci pipeline

- src/renderer/features/gm_toolkit/components/EncounterBuilder/EncounterNPCObject.vue
I also added a tooltip with full name of NPC to icon hover for the longer names
> Fixes #313

- build_scripts/build-content-schema.js
- src/renderer/classes/ContentPack.ts
- src/renderer/classes/npc/NpcFeature.ts
- src/renderer/classes/npc/NpcReaction.ts
- src/renderer/classes/npc/NpcSystem.ts
- src/renderer/classes/npc/NpcTech.ts
- src/renderer/classes/npc/NpcWeapon.ts
- src/renderer/features/_shared/store/index.ts
- src/renderer/features/nav/pages/ExtraContent/PackInfo.vue
- src/renderer/features/nav/pages/ExtraContent/PackInstall.vue
- src/renderer/io/ContentPackParser.ts
- src/renderer/schema.ts
- Allow for adding NPC data (classes, features, templates) with extra content packs
- Tweak NPC data interfaces for better schema generation
- Tweak schema definition and generation script to generate schemas for NPC data
> Allow NPCs in Extra Content

- src/features/pilot_management/New/index.vue
- src/features/pilot_management/New/pages/ConfirmPage.vue
Fixes the "your pilot will be lost" route guard in the new pilot wizard firing when the user clicks "register pilot" at the end of the process.
> Fix pilot wizard route guard firing when done

- src/features/pilot_management/PilotSheet/components/PilotHeader.vue
- src/features/pilot_management/Roster/components/PilotTable.vue
- src/router.ts
Fixes bug 31 (`In the Compact View of pilots you can't click on a pilot and open their pilot page`)
> v2 testing bug fixes

- README.md
Patreon badge was pointed at the wrong repo
> Fix Patreon badge & add Discord badge

- src/mixins/getColor.ts
- src/ui/components/CCBtn.vue
- src/ui/components/CCComboSelect.vue
- src/ui/components/CCDamageElement.vue
- src/ui/components/CCDialog.vue
- src/ui/components/CCExtendedTag.vue
- src/ui/components/CCGmHeader.vue
- src/ui/components/CCItemUses.vue
- src/ui/components/CCMajorBtn.vue
- src/ui/components/CCMechStatusAlert.vue
- src/ui/components/CCNotification.vue
- src/ui/components/CCPopup.vue
- src/ui/components/CCRangeElement.vue
- src/ui/components/CCRating.vue
- src/ui/components/CCShortStringEditor.vue
- src/ui/components/CCSimpleSelect.vue
- src/ui/components/CCSlashes.vue
- src/ui/components/CCSoloDialog.vue
- src/ui/components/CCStatblockPanel.vue
- src/ui/components/CCStatusSelect.vue
- src/ui/components/CCStepperContent.vue
- src/ui/components/CCStringEdit.vue
- src/ui/components/CCTag.vue
- src/ui/components/CCTags.vue
- src/ui/components/CCTickBar.vue
- src/ui/components/CCTitle.vue
- src/ui/components/CCTitlebar.vue
- src/ui/components/CCTitledPanel.vue
- src/ui/components/CCTooltip.vue
- tsconfig.json
Reverts massif-press/compcon#552
looks like this may be breaking something related to `getColor`. I'll check later today.
> Revert "Refactor base CC styled building block components to use VCC & VPD"

- src/classes/npc/NpcWeapon.ts
- src/ui/components/cards/_NpcWeaponCard.vue
- src/ui/components/cards/npc/cards/_WeaponCard.vue
> Swap Accuracy and AttackBonus for NPC weapon cards

- .travis.yml
Updates travis.yml for 2.0.0 release. Comments out Electron build/deploy step, fixes some stuff to make sure deploy on tag works.
> build(travis): update travis.yml for 2.0.0

- src/classes/ContentPack.ts
- src/classes/pilot/PilotEquipment.ts
All data was being loaded as PilotGear even if it was marked as armor or weapon. Adds the logic to
handle that properly.
Bug fix (non-breaking change which fixes an issue)
> Fix all data in pilot_gear.json being loaded as pilot gear

- src/ui/components/tables/CCRefStressTable.vue
- src/ui/components/tables/CCRefStructureTable.vue
- src/ui/components/tables/CCStressTable.vue
- src/ui/components/tables/CCStructureTable.vue
- src/ui/components/tables/_TableWindowItem.vue
- src/ui/components/views/CCSidebarView.vue
Refactors the base components under `/ui/components/tables/` and the `CCSidebarView` component under `/ui/components/views/` as class-style components. 
Part of #514 
Component refactors. May require revision if there were any pending changes to the ts code of these components in race condition with this PR.
> [VCC Refactor] UI Table components refactored to use VCC

- src/features/pilot_management/PilotSheet/sections/info/components/HistoryBlock.vue
Reported by user on Discord
None
> fix(Pilot Sheet): s/Biograpgy/Biography/g

- .gitignore
- src/ui/components/cards/CCActiveCard.vue
- src/ui/components/cards/CCItemCard.vue
- src/ui/components/cards/CCItemChip.vue
- src/ui/components/cards/CCItemModal.vue
- src/ui/components/cards/CCSearchResultModal.vue
- src/ui/components/cards/_PilotGearCard.vue
- src/ui/components/cards/_WeaponModCard.vue
Refactor PilotGearCard and WeaponModCard to use VCD and VCC. I dropped the name from each of these components because they're not intended to be used directly.
https://github.com/massif-press/compcon/issues/514
> Refactor PilotGearCard and WeaponModCard to use VPD and VCC

- src/classes/Damage.ts
- src/classes/Range.ts
- src/classes/Statblock.ts
- src/features/pilot_management/PilotSheet/components/StatblockDialog.vue
Adds the option to use Pilot NET Discord Emoji to display range and damage types in the generated statblock for PCs
https://github.com/massif-press/compcon/issues/694
> Statblock discord emoji

- build_scripts/build-content-schema.js
- src/class.ts
- src/classes/ContentPack.ts
- src/classes/Faction.ts
- src/features/compendium/Views/Factions.vue
- src/features/compendium/Views/Home.vue
- src/features/compendium/routes.ts
- src/features/compendium/store/index.ts
- src/interface.ts
- src/io/ContentPackParser.ts
- src/schema.ts
- src/shims/shims-modules.ts
feat(Compendium): adds factions to compendium
**Breaking**: lancer-data needs to include `factions.json`
cf: This pull request: https://github.com/massif-press/lancer-data/pull/126
Closes https://github.com/massif-press/compcon/issues/510
> feat(Compendium): adds factions to compendium

- src/ui/components/panels/loadout/pilot_loadout/CCPilotLoadout.vue
Closes #1426
Fixed reference string from "extendedharness" to "extended_harness". The remaining changes fix warnings and are refactoring for increased code reuse.
`#1426`
> fix(Pilot Sheet): make extra equipment from "Extended Harness" available

- src/features/pilot_management/Level/pages/ConfirmPage.vue
- src/features/pilot_management/PilotSheet/components/CloneDialog.vue
- src/features/pilot_management/PilotSheet/components/ExportDialog.vue
- src/features/pilot_management/PilotSheet/components/LevelEditDialog.vue
- src/features/pilot_management/Print/OptionsDialog.vue
Creates sync emitters for pilot level up (through the level up stepper) and level edit (through the level edit dialog).  Additionally modifies some Vue object names so that they are named clearly in Vue Devtools.
Closes #1574
> fix(Pilot Sheet): syncs pilot on level up/level edit

- src/classes/Background.ts
- src/classes/CompendiumItem.ts
- src/classes/ContentPack.ts
- src/classes/pilot/Talent.ts
- src/features/compendium/Views/Backgrounds.vue
- src/features/compendium/components/SidebarArrayView.vue
- src/features/ui_test/index.vue
- src/ui/components/Talent/components/_TalentFull.vue
- src/ui/components/Talent/components/_TalentMicro.vue
- src/ui/components/Talent/components/_TalentSmall.vue
- src/ui/components/Talent/components/_TalentTerse.vue
- src/ui/components/cards/_FrameCard.vue
- src/ui/components/cards/_MechSystemCard.vue
- src/ui/components/cards/_MechWeaponCard.vue
- src/ui/components/cards/_NpcSystemCard.vue
- src/ui/components/cards/_NpcTechCard.vue
- src/ui/components/cards/_NpcTraitCard.vue
- src/ui/components/cards/_NpcWeaponCard.vue
- src/ui/components/cards/_WeaponModCard.vue
- src/ui/components/selectors/CCBackgroundSelector.vue
This provides the source "book" of talents and backgrounds. ~~I believe this is all that is remaining as far as pilot side.~~ This should continue to help in the effort to help people struggling to import pilots with various LCPs.
It looks like what remains on the pilot side is the following:
Core Bonuses
Skill Triggers ( low priority, I don't believe any existing LCPs add skill triggers )
Pilot Armor
Pilot Weapons
Pilot Gear
> Identify source LCP / core book for pilot talents and backgrounds

- src/assets/generators/mechnames.txt
This adds the mech names I suggested in the linked issue.
https://github.com/massif-press/compcon/issues/1672
`#1672`
> [Feature] Add more mech names to random generator list

- src/features/encounters/mission/runner/index.vue
- src/features/main_menu/_components/login/SignIn.vue
- src/features/main_menu/_components/login/SignedIn.vue
- src/io/BulkData.ts
- src/io/Startup.ts
- src/user/index.ts
- src/user/store/index.ts
- src/user/sync.ts
Reverts massif-press/compcon#1712 in attempt to isolate memory leak
> Revert "fix(Cloud): overwrite Cloud data on data wipe/bulk import"

- src/classes/Action.ts
- src/classes/mech/ActiveState.ts
- src/classes/mech/Mech.ts
- src/ui/components/items/features/actions/_actionBase.vue
- src/ui/components/items/features/actions/_actionButton.vue
- src/ui/components/panels/loadout/active_loadout/components/_ActionDetailExpander.vue
This solves the top level complaint in #1585 and should handle a few other cases. It falls in one or two areas, but is still a step forward
Closes #1585
Closes #1555 
> fix(Active Mode): actually repect action refresh in active mode

- src/features/pilot_management/ActiveSheet/views/ActiveRest.vue
This fix applies a similar fix as the one that fixed #1616 to the Pilot HP ticker in Active Rest
state.
Closes #1740
> fix(Active Mode): fix pilot HP ticker during ActiveRest

- src/features/pilot_management/Roster/components/PilotCard.vue
- src/features/pilot_management/Roster/components/PilotListItem.vue
- src/features/pilot_management/Roster/index.vue
- src/features/pilot_management/store/index.ts
Reverts massif-press/compcon#1751
> Revert "fix(Pilot Sheet): Refactor Pilot groups for performance & roster improvements"

- src/features/main_menu/_components/login/SignIn.vue
- src/features/main_menu/_components/login/SignUp.vue
There have been a couple cases where new users have recently reported case-sensitivity issues on Pilot NET. This PR adds extra safety to Email signups, making sure to use a constant lowercase email address when creating a new account. In addition, it adds a debounce to the SignIn and SignUp methods while `loading` is true. Finally, it also wraps login and signup fields in a `v-form` tag, allowing for easy submission of credentials with the "Enter" key.
> fix(signup): debounce signin+up, use safe consts, forms

- src/features/compendium/components/CompendiumPageButton.vue
- src/features/compendium/components/views/components/CompendiumCard.vue
- src/features/encounters/components/HomeCard.vue
- src/features/encounters/mission/runner/Debriefing.vue
- src/features/encounters/mission/runner/index.vue
- src/features/encounters/npc/new/index.vue
- src/features/main_menu/_components/MainBtn.vue
- src/features/main_menu/_components/MainTitle.vue
- src/features/main_menu/desktop.vue
- src/features/nav/index.vue
- src/features/nav/modes/compendium.vue
- src/features/nav/modes/encounter.vue
- src/features/nav/modes/pilot.vue
- src/features/nav/pages/Help.vue
- src/features/nav/pages/Options/Settings.vue
- src/features/pilot_management/PilotSheet/components/PilotNav.vue
- src/features/pilot_management/PilotSheet/sections/mech/components/MechNav.vue
- src/features/ui_test/index.vue
- src/ui/components/CCBtn.vue
- src/ui/components/CCDialog.vue
- src/ui/components/CCRating.vue
- src/ui/components/CCStepperContent.vue
- src/ui/components/cards/CCItemCard.vue
- src/ui/components/selectors/views/components/CompendiumCard.vue
Many alterations to buttons to make them keyboard accessible. Changes are usually one of
- making an element tab focusable
- making the focus state of an element more visible
- making a button respond to the enter key
Resolves #1557 
---
I'm new to this project, and most of my experience has been on solo work, so please provide feedback. I probably have some blind spots.
> fix(accessibility) Add keyboard accessibility

- src/features/main_menu/_components/login/SignIn.vue
- src/features/main_menu/_components/login/Verify.vue
Added conditional display of link to Verification Code view. Standardized some wording.
Closes #2061
> fix(sign in): require email for verification code functions

- src/features/compendium/Views/Home.vue
- src/features/compendium/Views/PilotGear.vue
- src/features/compendium/Views/Statuses.vue
- src/features/pilot_management/Print/BlankPilotPrint.vue
This PR updates the "Pilot Gear" and "Statuses & Conditions" compendium page headers to match the headers used in the Lancer Core Book.
Closes #2141
> fix(compendium): Update pilot gear, status pg headers

- src/classes/npc/NpcItem.ts
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
#2250
> fix: add getTotalUses function to NpcItem

- src/classes/utility/ItemFilter.ts
- src/features/compendium/components/CompendiumBrowser.vue
- src/ui/components/panels/filters/_MechSystemFilter.vue
- src/ui/components/panels/filters/_MechWeaponFilter.vue
- src/ui/components/panels/filters/_WeaponModFilter.vue
Added two new filtering options to the Mech Weapons and Mech Systems filter pages, and also made it so pages in the compendium with a search bar can search for the License by typing it.
Each of the following features are a separate commit if the team decides any of them are not desired functionality:
- Added License Level option to the filter UI for both Mech Weapons and Mech Systems.  UI element behaves similar to the current SP Cost filter option.
- Added License option to the filter UI for both Mech Weapons and Mech Systems.  It is a multiple-select element like the Tags options, so multiple licenses can be selected to filter by if desired.
- The compendium search bar will now also search the license string(which includes both the license and license level) in addition to the current …
> feat: add license and license level filtering to mech weapons and systems compendium pages

- src/ui/components/selectors/views/_SelectorTableView.vue
Added some basic checks to determine if incoming value is actually a real number or not to improve sorting consistency.
#2257
> Resolve funky Mimic gun behavior when sorting damage/range
